### ISSUE TITLE
[New module system] Fixity rebalancing broken

### ISSUE THREAD

**Issue by m-yac** [GaloisInc/cryptol#1371]
In #1363 `tests/regression/repl-decls.icry` fails because:
```
let x -<- y = x - y; infixl 5 -<-; let (-<-) : Integer -> Integer -> Integer
let x ->- y = x - y; infixr 5 ->-; let (->-) : Integer -> Integer -> Integer

42 -<- 10 -<- 100
42 ->- 10 ->- 100
42 ->- 10 -<- 100
```
outputs
```
-68
-68
-68
```
instead of what is used to, which was:
```
-68
132

[error] at repl-decls.icry:6:4--6:7 and repl-decls.icry:6:11--6:14
    The fixities of
      • (->-) (precedence 5, right-associative)
      • (-<-) (precedence 5, left-associative)
    are not compatible.
    You may use explicit parentheses to disambiguate.
```

After a quick first pass through the renamer, I saw no reason why this PR would break the existing fixity rebalancing (none of the relevant bits seem to be changed) – but I'll be taking a deeper look soon.

**Comment by qsctr** [comment]
It seems like this only happens when the operators are defined at the REPL and not in a module.

**Comment by yav** [comment]
I think the problem might with the fixity of operators that are not defined at the top level.  For example, this seems to be incorrect also:
```
f = 10 .-. 2 .-. 1
  where
  infixr 5 .-.
  x .-. y = x - y
```
The result is 7 (i.e. `(10 - 2) - 1`) but it should be `9` (`10 - (2 - 1)`).

**Comment by qsctr** [comment]
Ok, the issue seems to be here: https://github.com/GaloisInc/cryptol/blob/70d96006a5526a94dc72d5ee3bc84096770b7e3b/src/Cryptol/ModuleSystem/Binds.hs#L157-L158

When we are processing the `TopDecl`s we pass `Nothing` as the `ModPath` but we really want `Just (TopModule m)` with the `m` from here
https://github.com/GaloisInc/cryptol/blob/70d96006a5526a94dc72d5ee3bc84096770b7e3b/src/Cryptol/ModuleSystem/Renamer.hs#L174-L182

just like the code in `master`
https://github.com/GaloisInc/cryptol/blob/cfb16318b5f67f762426d8a1386002e78e63bdf2/src/Cryptol/ModuleSystem/Renamer.hs#L86-L87

because the name binding code treats `Nothing` as meaning we are defining a local name.
https://github.com/GaloisInc/cryptol/blob/70d96006a5526a94dc72d5ee3bc84096770b7e3b/src/Cryptol/ModuleSystem/Binds.hs#L302-L307

which is actually the other issue that @yav pointed out, if we actually *do* happen to be defining a local name, then we do not record custom fixities. But currently in `master` we have the same code for that and don't support having local fixities either.
https://github.com/GaloisInc/cryptol/blob/cfb16318b5f67f762426d8a1386002e78e63bdf2/src/Cryptol/ModuleSystem/NamingEnv.hs#L378

So I guess I will open up another issue for that and fix this specific issue for now to behave the same as on `master`.

**Comment by qsctr** [comment]
Fixed in https://github.com/GaloisInc/cryptol/pull/1363/commits/4b3eac56f6d790216b225e00703cfcababc54375
