### ISSUE TITLE
Improve in-REPL documentation of :set commands

### ISSUE THREAD

**Issue by acfoltzer** [GaloisInc/cryptol#154]
Right now, `:help` displays docs for the various `:` commands, and `:set` (with no arguments) displays the current values of the various settings. However neither of these provides docs for what each of the `:set` settings does. We could either:
1. add an argument to `:help` so that we can pull up more detailed documentation for all commands, or
2. add the documentation to the `:set`-with-no-arguments output.

I'd be in favor of 1, as it'd give us room to have more detailed in-REPL docs overall.

**Comment by dylanmc** [comment]
+1: just encountered this trying to figure out :writeByteArray.

**Comment by brianhuffman** [comment]
As of a1bb918840aafd5c628e270b73d7726e32b182c0, we can now print help text for `:set` options:
```
Cryptol> :help :set ascii

     ascii = off

Default value: off

display 7- or 8-bit words using ASCII notation.
```

I'll close the ticket once I implement tab completion for option names with `:help`. Also, it would probably be good to support writing just e.g. `:help ascii` instead of `:help :set ascii`. (I'd like to support both, because I think typing `:help :set <TAB>` would be particularly useful.)

**Comment by brianhuffman** [comment]
Also, as of b302dc044ea26dd0b80744174f1983763a92a2dd we can print help text for any REPL command:
```
Cryptol> :help :reload

    :r, :reload

reload the currently loaded module
```
