### ISSUE TITLE
Improvements to notebook - TODO list

### ISSUE THREAD

**Issue by david-christiansen** [GaloisInc/cryptol#163]
The new notebook interface needs some improvments. Here's the notes from a quick meeting with @acfoltzer.

This is on top of #75 and #76, and is based on 7cd2739.

<div id="table-of-contents">
<h2>Table of Contents</h2>
<div id="text-table-of-contents">
<ul>
<li><a href="#sec-1">1. HOWTO</a></li>
<li><a href="#sec-2">2. Steps remaining for Cryptol notebook</a>
<ul>
<li><a href="#sec-2-1">2.1. Move away from putStrLn and friends for output</a></li>
<li><a href="#sec-2-2">2.2. Idris-style pretty printing (nice to have, not need to have)</a></li>
<li><a href="#sec-2-3">2.3. Additional commands</a></li>
<li><a href="#sec-2-5">2.4. Parser errors kill the kernel</a></li>
</ul>
</li>
<li><a href="#sec-3">3. Wishlist</a></li>
<li><a href="#sec-4">4. Improvements to the IPython interface</a>
<ul>
<li><a href="#sec-4-1">4.1. Make the contents of execCount (an MVar in EasyKernel) accessible as an extra arg to run</a></li>
</ul>
</li>
</ul>
</div>
</div>

# HOWTO<a id="sec-1" name="sec-1"></a>

Add the latest master of IHaskell's ipython-kernel lib using cabal
sandbox add-source, then build with the notebook flag enabled.

# Steps remaining for Cryptol notebook<a id="sec-2" name="sec-2"></a>

## Move away from putStrLn and friends for output<a id="sec-2-1" name="sec-2-1"></a>

Right now, Cryptol has lots of appeals to string output functions. The
notebook patch updates some of them to be configurable (see field `ePutStr`
on `REPL.Monad.RW`) but what is really needed is a system for
outputting different kinds of messages with different actions. For
instance, one for warnings, one for program output, one for evaluation
results, etc.  That way, they can be treated differently.

## Idris-style pretty printing (nice to have, not need to have)<a id="sec-2-2" name="sec-2-2"></a>

Semantic annotations on the pretty-printer can enable much nicer
output to the notebook. For instance, type annotations can appear in
tooltips and some types of documents might be displayed totally
differently (eg as a progress bar). Trevor has updated the `pretty`
library to support this style of working.

## Additional commands<a id="sec-2-3" name="sec-2-3"></a>

Help lookup and completion should be implemented.

## Parser errors kill the kernel<a id="sec-2-5" name="sec-2-5"></a>

Exceptions in parsing commands should be handled. To see the error,
evaluate `:fnord` as a command. The kernel crashes.

# Wishlist<a id="sec-3" name="sec-3"></a>

-   Show quotes from commands instead of char counts for errors
    occurring in commands (it might be easiest to represent errors as
    an error datatype rather than as pp docs, so they can be displayed
    by frontends)
-   Allow multi-line commands (like ielm does, using open brackets)
-   Proper CodeMirror editor mode
-   Fancy HTML output for commands like `:browse`
-   Bitmaps and progress bars

# Improvements to the IPython interface<a id="sec-4" name="sec-4"></a>

## Make the contents of execCount (an MVar in EasyKernel) accessible as an extra arg to run<a id="sec-4-1" name="sec-4-1"></a>

This makes the cell numbers visible.

**Comment by weaversa** [comment]
Feature requests:

  - support `prove` command and ilk.
  - option to turn off defaulting and shadowing warnings

**Comment by jpziegl** [comment]
@weaversa and I just played with this. Nice!

One thought: It would be useful to be able to export the notebook as a Cryptol (.cry) file. Maybe export as literate Cryptol to save all the output? Import would be nice as well.

**Comment by acfoltzer** [comment]
@weaversa: Huh. That's an odd regression with `:prove`, I'll look into that right away. The mass of warnings is something that will be addressed soon.

@jpziegl: I was pleased to learn that this actually already works to some extent. IPython's [`nbconvert`](http://ipython.org/ipython-doc/2/notebook/nbconvert.html) tool can be run on notebooks to export to a variety of formats. 

The `--to python` option even almost works, but uses Python comment characters which of course breaks the resulting Cryptol file, and includes the contents of command cells that wouldn't be valid at the top level of a Cryptol module. A quick sed script would be enough to take care of the first problem, but the second one would be trickier. Might be one for the next phase of work.

**Comment by weaversa** [comment]
In the notebook, what's the difference between
`x = 4`
and
`let x = 4`

The user experience is that one prints a bunch of warnings and the other issues silently.

**Comment by acfoltzer** [comment]
@weaversa: what's going on behind the scenes is that each cell is parsed either as a module like you'd write in a `.cry` file, or as a series of commands like you'd enter into the command line REPL.

Since `x = 4` is a valid top-level declaration, it's added to the module the notebook is building behind the scenes, triggering all the warnings as that module then gets reloaded. Note that in this case the warnings are not coming from the definition of `x`, but from other definitions that are part of that module.

Since `let x = 4` is a valid REPL command, that goes through without complaint since there are no other definitions to consider. The flipside to this is that as soon as we have to reload the module for another cell, this definition of `x` disappears, much like `:r` will wipe out any let-bound definitions at the command line REPL.

The advantage of having both is that you can let bind to names that are already defined elsewhere, which might be useful for pedagogical purposes (e.g., just use `x` over and over rather than having to use a new name each time). However I'm not sure that's worth the confusion of a) having two binding forms that look almost identical to the user and b) having one of those binding forms disappear when another cell is executed.

After thinking this through while writing this comment, I'm in favor of removing let bindings from the command language accepted by the notebook, much like we already exclude commands like `:l`, `:cd`, and `:!`. Does this sound good or am I missing other reasons to keep them?

**Comment by elliottt** [comment]
I agree with removing `let` from the command language accepted by the
notebook.  It seems like a strange feature in that context.

**Comment by weaversa** [comment]
I also agree w/ removing `let`.

**Comment by weaversa** [comment]
I'd like to add proper syntax highlighting to the wishlist. For example, the notebook thinks `#` is a comment, rather than concatenation.

**Comment by acfoltzer** [comment]
Cool, I'll take out `let` next week.

@weaversa: #77 has been on my personal wishlist for a while :+1:

**Comment by david-christiansen** [comment]
FWIW, I also think that removing the `let` command is a good idea.

**Comment by acfoltzer** [comment]
These have either already been completed, or have been split out into separate tickets: #166, https://github.com/GaloisInc/ICryptol/issues/2, https://github.com/GaloisInc/ICryptol/issues/3, https://github.com/GaloisInc/ICryptol/issues/4, https://github.com/GaloisInc/ICryptol/issues/6, https://github.com/GaloisInc/ICryptol/issues/7, https://github.com/GaloisInc/ICryptol/issues/8
