### ISSUE TITLE
Invalid Code Generated by :t

### ISSUE THREAD

**Issue by jpziegler** [GaloisInc/cryptol#177]
Removing the type definition of validMoveSequence from FoxChickenCorn.cry side-steps #175. However, asking for the inferred type results in the following, which is not valid Cryptol:

```
FoxChickenCorn> :t validMoveSequence
validMoveSequence : {a} (fin a) => [1 +
                                    a]FoxChickenCorn::BankState -> Bit
```

`FoxChickenCorn::BankState` looks like a Haskell artifact. Presumably, the types output by `:t` should be copy-paste-able.

**Comment by brianhuffman** [comment]
`FoxChickenCorn::BankState` is just a qualified name in Cryptol: it just means `BankState` from module `FoxChickenCorn`. Cryptol uses `::` instead of `.` for the qualified name separator because we already use `.` for record field selection.

**Comment by weaversa** [comment]
```
validMoveSequence : {a} (fin a) => [1 + a]FoxChickenCorn::BankState -> Bit
```
doesn't work. `BankState` by itself does:
```
validMoveSequence : {a} (fin a) => [1 + a]BankState -> Bit
```
I agree that the types output by `:t` should be copy-paste-able.

**Comment by brianhuffman** [comment]
I did some experiments, and I understand the issue now. Types like `FoxChickenCorn::BankState -> Bit` are perfectly valid Cryptol; the problem is that the qualified name `FoxChickenCorn::BankState` is not actually in scope in the place where it is used.

There are two places where we need to add more qualified names to the naming environment:

1. Qualified names of values and types within the same module:

        module A where
        type Byte = [8]
        x : A::Byte
        x = zero

  Currently this gives a `Type not in scope: A::Byte` error.

2. Qualified names of values and types from imports:

        module B where
        import A
        y : A::Byte
        y = zero

  This yields the same error message.

I believe that the REPL is supposed to give you the same naming environment that you have *inside* the loaded module, so this should fall under case 1.

**Comment by yav** [comment]
We should check with Trevor, but I believe both of those were conscious choices when we were designing Cryptol's module system, which is different from Haskell's.  This is how it works:

   *  `import A` imports the exported names of `A`, *unqualified*.
   * `import A as B` imports the exported names of `A`, *qualified* by `B`
   * I don't believe there is a way to use a qualified name to refer to the local module---if you want to avoid conflicts, you can use an `as` import.

I believe the reasoning for these design choices is that they are much simpler than Haskell's rules, and cover virtually all the name management you might want to do.

Examples:

    module A where
     x = 0x10

    module B where
       import A

      y = x  -- OK
      -- y = A::x  -- not OK

    module C where
       import A as A

      y = A::x -- OK
      -- y = x -- Not OK

**Comment by brianhuffman** [comment]
I always thought that `import A` would give you the names of `A` both qualified *and* unqualified. The current behavior is surprising to me (being used to Haskell and ML, I guess).

Anyway, if the consensus is to keep the current meaning of `import`, then the problem still remains that `:t` prints out types using a different naming environment than the one you have in the module or at the REPL.

**Comment by yav** [comment]
Yeah, that's a bug: it should only print the qualified names if the type was not in scope for some reason.

We should make a wiki page about how the module system works---there are other changes from Haskell too (e.g., we use ` private` declaration, instead of an export list, and local names always shadow imported ones, kind of as if the imports was in one big `where`).

**Comment by elliottt** [comment]
I changed the pretty printer to carry an environment describing how to print qualified names.  Now, when using `:browse`, or `:type` from the REPL, names are printed in a way consistent to the environment present in the loaded module.
