### ISSUE TITLE
Tab completion on check and friends

### ISSUE THREAD

**Issue by marsella** [GaloisInc/cryptol#1780]
Right now, the Cryptol repl supports tab completion within the `:prove` and `:exhaust` commands, but not for `:check` or `:type`. It would be a very nice quality-of-life improvement to add completion!

Related issue #781.

**Comment by RyanGlScott** [comment]
I think the reason that `:t` and `:check` fail to autocomplete is that there are multiple commands that have them as prefixes:

* `:t`: `:type` and `:time`
* `:check`: `:check` and `:check-docstrings`

As such, Cryptol refuses to commit to the autocompletion strategy for either command.

One way to improve this: if you have typed `:check rev`, then arguably you want the `:check` command, not `:check-docstrings`, due to the fact that there is a space after the `:check` prefix. If we see a situation where the a user has typed `:<CMD> ...` and `<CMD>` exactly matches a defined command (e.g., `:check`), then we should commit to that approach over any other ones (e.g., `:check-docstrings`).

I think this approach would also solve the `:type` versus `:time` problem. This is because Cryptol [explicitly defines `:t` as an alias of `:type`](https://github.com/GaloisInc/cryptol/blob/7f1daa22f492092bf97f1ad938df111b4b27cb47/src/Cryptol/REPL/Command.hs#L231), so `:t ...` should unambiguously pick `:type`'s autocompletion strategy.
