### ISSUE TITLE
Scoping issue

### ISSUE THREAD

**Issue by weaversa** [GaloisInc/cryptol#180]
```
Cryptol> False < False > True
Parse error at 1:17, unexpected True
```
I expected Cryptol to choose a scope, either `(False < False) > True` or `False < (False > True)`.

```
Cryptol> False < False >

Parse error at 3:0, unexpected end of file
```
It seems that `>` is parsed, but what is Cryptol expecting afterwards?

**Comment by brianhuffman** [comment]
Both `<` and `>` are declared as "nonassoc" in Cryptol's grammar. So it seems like the parser should fail immediately upon seeing `>`; I suppose it is just a quirk of the Happy-generated parser that it fails one token later.

**Comment by yav** [comment]
When the parser detects an error, it reports the location of the next available token.  I am guessing that here the error occurs after the `>` is consumed, which is why we report the error on the `True`.  Perhaps we should report the location of the last consumed token instead.  It is an easy change, let's see if it leads to more accurate errors.

**Comment by elliottt** [comment]
Since the support of user-defined operators, this error has changed to:

```
[error]
    The fixities of (at <interactive>:1:7--1:8, (<)) and
    (at <interactive>:1:15--1:16, (>)) are not compatible.
    You may use explicit parenthesis to disambiguate
```

as the operators aren't compatible. The choice to declare `(<)` and `(>)` as `infix` instead of `infixl` or `infixr` was somewhat arbitrary, and given that it makes sense to compare `Bit` typed things in Cryptol, we could choose one, and remove the error.

Thoughts?

**Comment by brianhuffman** [comment]
We should keep `<` and `>` as non-associative. We don't want to encourage anyone to write things like `False < False > True` which will be impenetrable to anyone who is not simultaneously looking at the table of operator fixities. The new error message is perfect.

**Comment by elliottt** [comment]
I agree. We can revisit the issue if anyone else feels strongly about it :)
