### ISSUE TITLE
Move to Z3 for the default solver?

### ISSUE THREAD

**Issue by LeventErkok** [GaloisInc/cryptol#196]
@weaversa

The good folks at Microsoft just announced that Z3 now comes with a MIT license and is now on github: https://github.com/Z3Prover/z3

Moving to z3 might be a good choice, both as the default solver for :sat/:prove etc., and in the type-checker. I really only regularly test SBV with Z3 in reality, and also with Microsoft's backing, it's more likely to be kept up-to-date and receive regular improvements. CVC4 is fantastic, but might suffer from the fact that it's an academic project.

Just a thought..

**Comment by atomb** [comment]
Another benefit of Z3 is that it's substantially easier to build on a variety of platforms. Avoiding the need to keep CVC4 up-to-date on all of the build and test machines here will save a lot of time. So, +1 from me!

**Comment by acfoltzer** [comment]
This seems like the right idea in the long term. Let's wait until the transition settles down a bit and binaries are available under the new license, but in the meantime maybe switch to Z3 for the typechecker on `wip/cs`. @yav, does that sound good?

**Comment by weaversa** [comment]
> switch to Z3 for the type checker

:+1:  :+1: :+1:

**Comment by LeventErkok** [comment]
It occurs to me you can also switch to ABC as well; as the default solver.

I guess the type-checker needs unbounded ints, so it has to stay with CVC4 or Z3.

**Comment by weaversa** [comment]
I want to put this statement somewhere -- I noticed that the command I deduced for ABC will time out on very hard problems (a few hours maybe?). So, maybe not a good choice for the default solver?

**Comment by LeventErkok** [comment]
@weaversa How do the other solvers do for those hard problems?

**Comment by acfoltzer** [comment]
I also wouldn't want to make ABC the default solver due to the relative difficulty of distribution for the platforms we support. The new user experience is hard enough with having to install two things ;)

**Comment by thoughtpolice** [comment]
Random outsider: I would really like this for the reasons @atomb suggested, because as a package maintainer, getting CVC4 to build is proving to be a nightmare for NixOS, because it wants to do all sorts of odd stuff like `wget` binaries. On the other hand, the Z3 expression (that I maintain) for Nix is beautiful and simple and very easy to support, and I can have Cryptol working out of the box with it.

Another advantage to it being easy to build and MIT licensed is that you could probably just build a private copy on your buildbots and ship it with released binary distributions (an extra `cryptol-z3` binary), which would be a huge win too IMO, since you can QA it much more easily.

**Comment by elliottt** [comment]
Cryptol-2.3.0 has switched to using z3 as the default solver.
