### ISSUE TITLE
Allow ranges to use non-literals: `[0..~zero]`

### ISSUE THREAD

**Issue by TomMD** [GaloisInc/cryptol#207]
I want to write code in the form:

    vector = [if idx == somethingExpliciltyTyped then val else otherVal | idx <- [0..~zero] ]

Since the type of the list is known `~zero` is rather similar to a constant.  I'm not sure how worth while it is to support simplification on expressions to allow non-literals in ranges but that is what this enhancment/request boils down to.  Any pointers are appreciated.

I've assigned myself but if you are interested and have time then talk to me and take it.

**Comment by brianhuffman** [comment]
I should point out that some non-literals are allowed in ranges:

    Cryptol> [0..2+3]
    Assuming a = 3
    [0x0, 0x1, 0x2, 0x3, 0x4, 0x5]

But note that `2+3` is a *type* expression (of kind `Nat`) and not a value expression; that's why 2+3 equals 5 instead of wrapping around to 1. In addition to `+`, you can also use `width`, `lg2`, `-`, `*`, `/`, `%`, `min`, and `max`, all of which are type operators that happen to share syntax with some value-level primitives.

We could debate whether `[_.._]` taking type arguments is a good idea. Having it take value arguments instead would be less surprising/confusing for programmers (and also more consistent with infinite streams like `[_...]`) but implementing that properly would be a serious undertaking: Because the typechecker needs to be able to statically compute lengths, we would need to extend Cryptol's type system with a notion of *phase* (static vs. dynamic) that is orthogonal to an expression's type. This would also make it more challenging to formalize the type system semantics.

Overall, I would be in favor of a change like this. It would take a fair amount of language and type system design work, but personally I think it would be a fascinating project to work on.

**Comment by weaversa** [comment]
You may be able to get your desired functionality through the current type system. Have you tried something like:
```
vector : {a, b} (fin a, fin b, b == 2^^a-1) => [b+1]
vector = [ if idx == (zero:[width b]) then True else False | idx <- [0..b] ]
```

**Comment by yav** [comment]
As Brian pointed out, the operators in list enumeration work on natural numbers without modulo-arithmetic (i.e., they never overflow).  I don't think that `~zero` makes a lot of sense in that setting.

I suspect that what you mean to write is `[ 0 .. ]`.  This means go from `0` to the largest element that will fit in the given bit-width.

If you want to write complex enumerations that use ordinary arithmetic and dynamic values, you can write them by combining `take` and `...`.  For example:

    myEnum : {n} fin n => [64] -> [n][64]
    myEnum x = take`{n} [ x  ... ]
 
   Main> myEnum`{3} 5
   [0x0000000000000005, 0x0000000000000006, 0x0000000000000007]

I am skeptical about doing the phase analysis, if this would mean that one has to use modulo arithmetic in enumerations:  in my experience this is a very common source of mistakes, as one has to be very careful in the boundary cases, which are common when writing enumerations.

I do think it would be interesting to explore the direction that Brian suggests, if we were to also extend Cryptol with a type for unbounded natural numbers and decide on some operations for them.  Then, a back-end that does not support arbitrary size numbers could attempt to eliminate them by specialization (exactly what we do with types at the moment), except that specialization in this case would amount to partial evaluation.
