### ISSUE TITLE
:writeDIMACS feature should be added

### ISSUE THREAD

**Issue by TomMD** [GaloisInc/cryptol#240]
In addtion to:sat, a `:writeDIMACS` feature would be useful in cases where you want to access a SAT solver, which often speaks only DIMACS.

Example use:

```
let f a b c = ~a || b || ~c && a | b || ~c && c || ~a || ~b
:writeDIMACS foo.dimacs f 
```

Then you'd get (I'm just trying to remember dimacs from a year ago here...)

```
$ cat foo.dimacs
c a=1 b=2 c=3
p 3 3
-1 2 -3 0
1 -2 -3 0
-1 -2 3 0
```

**Comment by weaversa** [comment]
```
p cnf 3 3
```
`abc` gives it for free, and is what's used when translating for the `external_cnf_solver` command.

**Comment by acfoltzer** [comment]
My sense is that this would be a better fit either for SAWScript. We want to avoid adding new backends to Cryptol as much as possible to avoid the feature accretion that burdened Cryptol 1, but SAWCore is intended to be an IR for many different formats.

**Comment by atomb** [comment]
This is already available in SAWScript, and is available easily because we link to ABC and have translations from SAWCore to ABC's internal representation. Within Cryptol, this would require implementing new infrastructure to translate Cryptol into a bit-level problem (since the current solvers, working through the SBV library, work entirely at the word level).
