### ISSUE TITLE
Symbolic execution of indexing operations takes exponential time

### ISSUE THREAD

**Issue by weaversa** [GaloisInc/cryptol#250]
```
Cryptol> :sat \(x:[32]) -> [1]@x == 1
```

Granted, I realize the obvious problem...but why is symbolic execution hanging? Lowering the size of `x` to something like `[15]` gives no slowdown.

**Comment by weaversa** [comment]
Better example, to show the out of bounds is not the issue ---
```
Cryptol> :sat \(x:[32]) -> ((x-0)%2) > 1
Unsatisfiable
Cryptol> :sat \(x:[32]) -> [1,2]@((x-0)%2) > (1:[2])
<hang>
```

**Comment by weaversa** [comment]
Works fine in `saw`.
```
sawscript> sat abc {{ \(x:[32]) -> [1,2]@((x-0)%2) > (1:[2]) }}
Sat: 1
sawscript> sat cvc4 {{ \(x:[32]) -> [1,2]@((x-0)%2) > (1:[2]) }}
Sat: 1
sawscript> sat z3 {{ \(x:[32]) -> [1,2]@((x-0)%2) > (1:[2]) }}
Sat: 1
```

**Comment by brianhuffman** [comment]
It looks like the running time is exponential in the bit-width of the index. 24 bits took a few seconds, so I guess 32 bits would finish in less than an hour.

Anyway, I tried `:set prover = offline`, and the generated smt is nice and small: linear in the index width (lookups turn into a tree of if-then-elses on the index bits). So the implementation of `@` in the symbolic backend must be losing some sharing somewhere, which is then recovered by the SBV library when the smtlib output is generated.

I'll have a look at the implementation of `@` and compare it with the one in SAW; we should probably do it the same way in both.

**Comment by brianhuffman** [comment]
Looking at `Cryptol/Symbolic/Prims.hs`, it seems that the function `selectV` is the source of the problem. It always constructs the full if-then-else tree for the given argument size, i.e. 2^32 elements for a 32-bit index. We just need to add a max-index argument so that we can prune the parts of the tree that correspond to indexes that point past the end of the list.

You will probably see a similar efficiency problem with shifts and rotates, since they are also defined with `selectV`.
