### ISSUE TITLE
Possible error in ChaCha20+Poly1305 IETF specification

### ISSUE THREAD

**Issue by thoughtpolice** [GaloisInc/cryptol#272]
Consider the following snippet:

```
// Pad a block of data
pad (m : [n][8]) = m # (zero : [(16-n%16)][8])
```

This is basically pulled from the ChaCha20/Poly1305 `AeadConstruction` in your sample. The specification reads:

> the padding is up to 15 zero bytes, and it brings the total length so far to an integral multiple of 16. If the length of the AAD was already an integral multiple of 16 bytes, this field is zero-length.

However, this does not work as intended. Consider the following:

```
Loading module Cryptol
Cryptol> let pad (m : [n][8]) = m # (zero : [(16-n%16)][8])
Cryptol> :t pad
pad : {a} (fin a) => [a][8] -> [a + (16 - a % 16)][8]
Cryptol> :t pad (zero : [15][8])
pad (zero : [15][8]) : [16][8]
Cryptol> :t pad (zero : [16][8])
pad (zero : [16][8]) : [32][8]
```

In the second case, the input is a multiple of `16` yet expands to `32` bits of data. This seems to be an error.

I have had quite a lot of trouble with this because I need the same thing for `BLAKE2`. Essentially, the padding there requires you to pad a message up-to a multiple of the block length, but only if it wasn't already a multiple of the block length. I've been scratching me head on how to do this, so I think I'm missing something very obvious.

Am I missing something? And can anyone enlighten me how to *actually* write a padding function that behaves as I described? I think you need it, and I do too :)

**Comment by TomMD** [comment]
I'll look at this issue, but would it be easier if we simply gave you blake2.cry?

**Comment by thoughtpolice** [comment]
That's not as much fun (I'm translating it from the book ATM, which is my real motivation.) :) Although I was asking for the answer on this... But now it more about the mystery behind how to do the padding than BLAKE2! Because I looked at this and thought it was correct at first glance. This has been a good exercise.

I'm just confused by the form the constraints have to take for something like this. I could probably do the padding another way, but I'm now wondering about this. BLAKE-256/512 actually has a much more 'complex' padding function, but it's 'easy' because it hinges on one fact: you're always padding up to the *next* multiple of the block size, because you *always* at least append 66-bits of data. IOWs, the difference is BLAKE2 pads *only if needed* where as BLAKE always pads.

Either way, don't mind me much. I'll figure it out (it would probably be easier to formulate the constraint by inlining the padding inside the hash function before compression), but when I tried to find a solution to this I came across this problem in your specification because RFC 7839 needs the same thing (I actually specified that recently too, so it was fresh on my mind.) If the implementation is correct, then I'm doing something wrong in my reading and need to take a step back...

**Comment by iblumenfeld** [comment]
I believe that changing it to [(16 - n%16)%16] will work.


Ian Blumenfeld
mobile +1 410 948 8460
direct +1 443 884 6872

CyberPoint International
621 East Pratt Street, Suite 300
Baltimore MD 21202-3140
phone +1 410 779 6700
www.cyberpointllc.com <http://www.cyberpointllc.com/>

________________________________________

If you believe you received this e-mail in error, please notify the sender
immediately, delete the e-mail from your computer and do not copy or
disclose it to anyone else.

The information in this email constitutes the proprietary information of
Cyber Point International, LLC (DBA CyberPoint), and should be accessed
only by the individual to whom it is addressed. The information in this
email and any attachments may not be used, copied or disclosed without the
consent of CyberPoint. CyberPoint is not responsible for any damages
caused by your unauthorized use of the materials in this email.

**Comment by iblumenfeld** [comment]
I believe that changing it to [(16 - n%16)%16] will work.  That's what I did in the Cryptol GCM implementation for padding.

**Comment by thoughtpolice** [comment]
The fastest gun in the west! Yep, that fixed it! I guess it was way to late in the night last night to think properly... (and with that, I can easily parameterize `pad` over the block size). I do believe that's the correct fix for the IETF specification as well. Thanks a lot!
