### ISSUE TITLE
:set prover=any doesn't seem to achieve parallelism

### ISSUE THREAD

**Issue by dylanmc** [GaloisInc/cryptol#277]
Platform: MacOS
scenario: a really hard :sat problem

What I'd expect to see: each of the SMT solvers I have installed, using all of my CPU.
What I actually see - one at a time:

  PID USER     PRI  NI  VIRT   RES   SHR S CPU% MEM%   TIME+  Command
51116 dylan     31   0 3186M  650M     0 R 100.  4.0  0:01.94 /Users/dylan/bin/boolector --sm
... (no sign of z3, abc, cvc4 or yices)

**Comment by acfoltzer** [comment]
So, I uncovered one bug that was preventing Cryptol from even trying to be parallel, but it still doesn't appear to actually be invoking the solvers in parallel.

We use `sbv`'s `allSatWithAny` and `proveWithAny` for this. @LeventErkok, do you have any ideas? I also notice with `debug=on` that it looks like symbolic simulation on the SBV side is occurring multiple times:

```
TripleDES> :sat \x y z w -> blockEncrypt (x,y,z,w) == zero
Simulating...
Trying proof with Z3, Yices, CVC4, ABC
** Checking Satisfiability, all solutions..
** Checking Satisfiability, all solutions..
** Checking Satisfiability, all solutions..
** Checking Satisfiability, all solutions..
** Starting symbolic simulation..
** Starting symbolic simulation..
** Starting symbolic simulation..
** Starting symbolic simulation..
```

**Comment by LeventErkok** [comment]
@acfoltzer @dylanmc  It is true that SBV will run the simulation for each solver even in parallel mode. The reason is that the configuration could differ. For instance you can do this:

```
proveWithAny [z3{solverTweaks=["SOMETHING"]}, z3{solverTweaks=["OR_OTHER"]}]
```

Basically, simulation can produce different outputs for different solvers depending on the configuration and also the actual characteristics of the solver itself. (For instance z3 allows "tactics" that you can pass, while others don't.)

I agree that for most use cases the simulation will produce exactly the same output so it's a waste, but this is more general.

Regarding why you guys don't see all solvers running: I really have no idea. I just tried the following:

```
$ ghci
GHCi, version 7.10.2: http://www.haskell.org/ghc/  :? for help
Prelude> :m Data.SBV
Prelude Data.SBV> proveWithAny [z3,cvc4] $ \a b c n -> (a .^ n + b .^ n) ./= ((c::SWord64) .^ (n::SWord64))
```

and when I do a `top` I can see both z3 and cvc4 are executing at the same time. Can you run this on your machine and report what you see?

**Comment by acfoltzer** [comment]
Hmm, I indeed get the parallel runs when running directly through `ghci`. I am puzzled why there's different behavior in Cryptol, unless the `Data.SBV.Dynamic` implementation is doing something differently. I'm on another project so I can't look too much further into it at this point, but I'll make sure to investigate when I'm back on.

**Comment by LeventErkok** [comment]
@acfoltzer @dylanmc 

I looked into this a bit more, and it appears to be a problem with `allSatWithAny` in SBV. I opened an SBV ticket: https://github.com/LeventErkok/sbv/issues/194

In the meantime, you can do the following work-around: If prover is set to any, and the user requests only one solution (the default, I believe), then call `satWithAny` instead of `allSatWithAny`. This shouldn't be a lot of coding, and I trust this'll fix the issue.

In case the user asks for more than one satisfying solution, then this workaround will of course not work.. Hopefully I'll be able to fix the SBV bug sometime soon for that scenario.

**Comment by LeventErkok** [comment]
@dylanmc @acfoltzer 

OK, the issue here is SBV's `allSatWithAll` and `allSatWithAny` functions. Cryptol only uses the latter; but both of these functions "naturally" sequentialize their output, so parallelizing them over the solvers is rather a tricky thing. It comes to the fact that `allSat` calls never fail (unless the solver dies), i.e., they return an empty-list at the worst case. Thus, when `allSatWithAny` runs, it sees that the very first solver that established communication, whichever it is, will be producing the result; so, it kills the other solvers, and keeps waiting on the first one. This is what Dylan was observing. A rather interesting gotcha.

I guess one can "re-architect" these functions to be lazier; but I don't see much point in that.

The solution is that you should not use `allSatWithAny`, but rather just `satWithAny`, which will nicely parallelize. Of course, this isn't compatible if the user asked for multiple-satisfying assignments. But, I think that's just how it should be: If the user wants multiple solutions, then Cryptol should stick to precisely one solver, and not use ":set prover=any".

The fix will be something like this:

  * If prover = any, num-solutions >1, tell the user "unsupported"
  * If prover = any, num-solutions = 1, use satWithAny.
  * If prover /= any, num-solutions >1, then use allSat. Note that there'll be only one solver in this case.

I already pushed a commit to SBV to remove `allSatWithAll` and `allSatWithAny` functions.

This shouldn't be a lot of coding, but let me know if you see any issues!

**Comment by LeventErkok** [comment]
@acfoltzer sbv 5.1 just got released; which removes `allSatWithAll`, which means Cryptol won't build against it. fyi.

**Comment by LeventErkok** [comment]
@acfoltzer I think this ticket is good to close now; no? Are there still issues?

**Comment by acfoltzer** [comment]
Indeed, thanks!
