### ISSUE TITLE
feature request: fresh name generation

### ISSUE THREAD

**Issue by dmwit** [GaloisInc/cryptol#287]
It would be handy to have a top-level `ModuleCmd` (or `ModuleT` action) for generating fresh names. At the moment, I have defined

```
cryptolId :: Expr PName
cryptolId = EFun [PVar (Located emptyRange (ident "x"))] (ETyped (EVar (ident "x")) TBit)
```

and match the result of `checkExpr cryptolId` against the pattern `EAbs x _ _` to pull out a fresh name, but that feels very much like a hack.

**Comment by elliottt** [comment]
This is implemented in the context of the repl in the Cryptol.REPL.Monad  module (https://github.com/GaloisInc/cryptol/blob/master/src/Cryptol/REPL/Monad.hs#L456-L459). I think it would be pretty easy to migrate it out of there and into a more generally applicable place.

**Comment by brianhuffman** [comment]
I recently had a need to do name generation for something in saw-script, and I did it using functions `liftSupply` and `mkDeclared`/`mkParameter` from module `Cryptol.ModuleSystem.Name`. In your case, since you are generating a local variable, you probably want to use `mkParameter` instead of `mkDeclared`:

    newName :: Ident -> Range -> ModuleM Name
    newName i = liftSupply (mkParameter i r)

**Comment by atomb** [comment]
I think @brianhuffman's comment covers @dmwit's original request.
