### ISSUE TITLE
Increase typechecking performance for Cryptol::Extras

### ISSUE THREAD

**Issue by acfoltzer** [GaloisInc/cryptol#302]
The definitions added in #299 wound up split out into the `Cryptol::Extras` module due to the performance regression they introduced (speed of typechecking the Prelude is of very high priority because it happens so often). Let's work on improving performance of the typechecker further, and then merge these definitions back into the regular Prelude. (cc @TomMD)

**Comment by TomMD** [comment]
The Cryptol::Extras module can not be imported without something like `CRYPTOLPATH=$repo/lib`.  Is it easy to add the Extras module to wherever the prelude is installed so its in scope?   Once that's done I'll add extras as an import to Minilock/* so it loads properly.

**Comment by TomMD** [comment]
@acfoltzer mentioned to me that the bindist should locate Cryptol::Extras fine and the issue is probably limited to cabal-install users.  @elliottt, I think adding Extras.cry to [Cryptol/Prelude.hs](https://github.com/galoisinc/cryptol/blob/master/src/Cryptol/Prelude.hs) would fix the issue - thoughts?

**Comment by atomb** [comment]
Type checking `Cryptol::Extras` is now pretty quick. It seems to take about 0.05s on my machine (comparing the load time of `cryptol` with no arguments to running it on a file containing only `import Cryptol::Extras`).
