### ISSUE TITLE
Type checker does not infer (fin (a/2))

### ISSUE THREAD

**Issue by msaaltink** [GaloisInc/cryptol#314]
Even if I try really hard to tell the type checker that a/2 will be finite, it still complains:

```
f: {a} (fin a, a>=2, fin (a/2)) => [a][8] -> [8]
f xs = ys!0 where
  ys: [a/2][8] 
  ys = zero
```

Here's what it says:

```
[error] at ./bug8.cry:13:3--13:12:
  Failed to validate user-specified signature.
In the definition of 'Main::ys', at ./bug8.cry:13:3--13:5:
  fin a`193
    arising from
    use of partial type function /
    at ./bug8.cry:12:8--12:11
```

(those line numbers refer to the last two lines, type declaration and definition of `ys`).

I'm not sure what else I could write to help the type checker get this.

**Comment by jpziegler** [comment]
For what it's worth, this works:
```
f: {a,b} (fin a, fin b, a>=1, a==b/2) => [b][8] -> [8]
f xs = ys!0 where
  ys: [a][8]
  ys = zero
```
I believe it's equivalent.

**Comment by robdockins** [comment]
I've run into similar issues when using subtraction.  The root issue, I think, is the fact that Cryptol views subtraction and division as partial functions and has a hard time demonstrating when they are defined.  I would expect Cryptol to notice that 2 is not equal to 0, and that the division is defined; but it seems not to do that.  Likewise, even if we assert ``m <= n``, Cryptol is not willing to commit to the fact that ``n - m`` is defined.

By adding something like ``a == b/2`` in the assumption list, Cryptol gets to _assume_ that ``b/2`` is defined instead of having to prove it; essentially, the proof obligation for showing that ``b/2`` is defined is shifted to the calling context.

**Comment by jpziegler** [comment]
I was a bit surprised to find that this is accepted, with no minimum size of the input array:
```
f: {a,b} (fin a, b==a/2) => [a][8] -> [8]
f xs = ys!0 where
  ys: [b][8]
  ys = zero
```
As you'd expect, at runtime if you pass in a list of fewer than 2 elements, you get an "invalid sequence index" error. Should the type checker infer the constraint `b>=1` because it is indexed? Of course, if it was `ys!1` instead of `ys!0`, even that constraint wouldn't be good enough, so I can see why that might get tricky.
