### ISSUE TITLE
`install` target in the Makefile does not work

### ISSUE THREAD

**Issue by yav** [GaloisInc/cryptol#328]
The `install` target of the Makefile fails.  It would appear that it is looking for things that do not exist, perhaps it was not updated when we made the packaging system?

```
make install PREFIX=$HOME/tools/cryptol-2.4.0
[ -n "/home/diatchki/tools/cryptol-2.4.0" ] \
          || (echo "[error] Can't install without PREFIX set"; false)
(cd cryptol-2.4.0-Linux-x86_64_0ba8d97/home/diatchki/tools/cryptol-2.4.0; \
          find .          -type d -exec install -d        /home/diatchki/tools/cryptol-2.4.0/{} \; ; \
          find bin   -not -type d -exec install -m 755 {} /home/diatchki/tools/cryptol-2.4.0/{} \; ; \
          find share -not -type d -exec install -m 644 {} /home/diatchki/tools/cryptol-2.4.0/{} \;)
find: ‘bin’: No such file or directory
```

**Comment by acfoltzer** [comment]
So, this can be fixed by doing a `make clean` followed by reissuing the same command.

Basically, the Makefile has grown to the point that it contains logic that ought to be in a configure script instead. If the value of `PREFIX` changes between invocations, e.g., `make; make install PREFIX=foo`, it can cause things like this because the first `make` invokes `cabal configure` without a prefix, and then the second `make` doesn't know to reconfigure now that the prefix is present.

We should add a configure script to handle these things so that we're not pushing `make` past its breaking point. I'm going to track that in #351
