### ISSUE TITLE
Unbounded integer type?

### ISSUE THREAD

**Issue by acfoltzer** [GaloisInc/cryptol#347]
Would it be useful and/or feasible to add an unbounded integer type to Cryptol?

**Comment by LeventErkok** [comment]
Just my "outside lurker" thoughts..

There were two main reasons why Cryptol-1 never had unbounded integers:

- The desire to compile to FPGAs, or to HW in general; where the notion of an unbounded bit-vector just doesn't exist.

- The desire to have the symbolic backend work on all Cryptol programs; and with only a SAT solver at hand, unbounded integers were not an option.

Looks like the landscape changed since then, however:

- With Cryptol-2, I think the HW-compilation path is mostly shelved; so that's more or less not an issue anymore. (Of course, supporting FPGA backends again is a topic very much worthy of discussion, especially considering the next-gen chips from Intel will likely come with FPGA fabrics bolted onto them, making them much more attractive as a Cryptol target. But that discussion is beyond the scope of this ticket.)

- Now that Cryptol goes thru SMT solvers for its proof needs, unbounded integers is not an issue since SMT solvers (and SBV) do support reasoning with such quantities. There are some caveats however: While the linear integer problems are decidable, nonlinear fragments might end up returning `Unknown` from the solver. So, your users will have to understand that non-linear integer programs may or may not have an effective prover assoiciated with them. (Of course quick-check would still work.)

All in all, I think it would be good for Cryptol2 to support unbounded integer types; though one thing to watch would be to warn users not to abuse them and start treating Cryptol as a general purpose language that can do magic things (when it comes to compilation/proofs) when such unbounded quantities are allowed. When judiciously used, however, it can add significant expressive power and make it more easier to approach/use by newcomers who cannot be bothered with the fact that `1 + 1` *is* `0`.

**Comment by brianhuffman** [comment]
An initial implementation of an `Integer` type for cryptol is available in branch "integer": https://github.com/GaloisInc/cryptol/tree/integer

Here are the features that are implemented so far:
* type `Integer`
* instance `Arith Integer`
* instance `Cmp Integer`
* primitive `toInteger : {a} (fin a) => [a] -> Integer`
* primitive `fromInteger : {a} (fin a) => Integer -> [a]`
* primitive `integer : {val} (fin val) => Integer` (a variant of `demote` for type `Integer`)

Some features currently only work for concrete (not symbolic) values:
* bitwise operations (and, or, xor)
* `toInteger` and `fromInteger` (this depends on LeventErkok/sbv#233)

It would also be nice to generalize some other Cryptol primitives so that they can work with either `[n]` or `Integer`:
* list indexes for `@`, `!`, `@@`, `!!`, and `update`
* shift and rotation amounts for `<<`, `>>`, `<<<`, and `>>>`
* list enumerations `[x...]`, `[x,y...]`, `[a..b]`, and `[a,b..c]`
* numeric literals with `demote`
We could introduce a new class (maybe `Index a`) that would have instances for `[n]` and `Integer`, and generalize the types of the above primitives to use this class constraint, for example:
```
primitive (<<<) : {n, a, b} (fin n, Index b) => [n]a -> b -> [n]a
primitive (@) : {n, a, b} (Index b) => [n]a -> b -> a
```

**Comment by weaversa** [comment]
An `Index` type would get rid of a lot of those pesky defaulting warnings.

**Comment by brianhuffman** [comment]
If we added an `Index` class, we would need to decide how to implement defaulting for it. @robdockins has suggested that polymorphic values with `Index b` constraints should default to type `Integer`. For example, the polymorphic expression `1+1` could evaluate to `2:Integer` instead of `0:[1]`.

**Comment by LeventErkok** [comment]
@brianhuffman As I mentioned in https://github.com/LeventErkok/sbv/issues/233, SBV already supports `int2bv`/`bv2int` via `sFromIntegral`. Let me know if it's not working for some reason.

Also note the caveat that Z3 (and pretty much all solvers) treat `int2bv` as uninterpreted; so you should at least be issuing a warning to the user as it can cause spurious counter-examples.

**Comment by brianhuffman** [comment]
As of 940b9c80ec383b9e110e4d8df74dcb4cc764d8d8, the integer branch has now been merged into master. The implemented feature list is basically the same as what I described in my post from last August, except that there is (at least for now) no `Logic Integer` instance, so bitwise operations are not available in either symbolic or concrete evaluation. (We do have a `Zero Integer` instance.)

**Comment by brianhuffman** [comment]
Cryptol has an `Integer` type now, so I'm closing this ticket. Generalizing the types of `demote` and the indexing primitives are now separate tickets (#482 and #502, respectively).
