### ISSUE TITLE
Evaluation performance issue

### ISSUE THREAD

**Issue by msaaltink** [GaloisInc/cryptol#358]
With the new evaluator, most expressions I've tried take about the same time as the old.  I have one notable exception, from some code from issue #310:

    aset_multi_sorted a alist = [e | (e,_) <- xs] where
      key = [k | (k,_) <- alist]
      val = [v | (_,v) <- alist]
      // xs is a list of (element value, index_of_next_update) pairs
      xs =  [if (if j < width key then i == key @ j else False) // (**)
                then (val@j, j+1)
                else (e, j)
               | (_,j) <- [(zero,0)] # xs
               | i <- [0 ..]
               | e <- a ]

I used to be able to run this, and other variants, on 'a' and 'alist' with hundreds of elements.  The other variants still run fairly quickly on large examples, but for example `aset_multi_sorted [1 .. k] [(0x10,0x00)]` behaves poorly with increasing `k`.  On my machine, running cryptol rev 2e15d4f, this takes around 3s for k=79, 6s for k=80, 11s for k=81, and the time seems to continue to double for each increment of `k`.

As a side note, the line marked ** used to be written `if j < width key && i == key @ j`.  I think in the old evalutor `&&` did not evaluate its right argument when the left was false, whereas now `&&` seems to be strict.  That's not a necessarily a bad thing, and corresponds to the notes on the CryptolSemantics wiki, but I wonder if there were other changes to strictness.

**Comment by robdockins** [comment]
I did a quick experiment.  The exponential time behavior is due to this particular example using a sequence in a way that requires unbounded recall of previously-computed elements.

The new evaluator maintains a bounded LRU cache of previously-accessed elements for sequences, whereas the old evaluator would retain the value of every previously-visited element.  The LRU cache is currently hard-coded to retain 64 elements.  The exponential behavior of this example begins once `k` exceeds 64 elements and we start recomputing values.  If I increase the bound of the LRU cache, the examples start to run fast until the cache bound is again exceeded.

An LRU cache works great for common examples where a recursive definition is given that only touches elements within a short window, and significantly reduces retained memory in such cases.  However, for examples like this (where arbitrary elements get touched repeatedly) it does rather poorly.

Potential fixes:
1. "Don't do that" Don't try to support unbounded recall for sequences.  An easy fix (nothing to do!), but perhaps not very satisfying.
2. Increase the default cache size.  Set the default cache size to thousands or millions, pushing the memory/time tradeoff slider in the other direction.
3. Use an unbounded cache.  Throw the memory/time slider all the way.
4. Make caching strategy user-configurable somehow.
5. Dynamically resize caches.  Increase the cache size progressively if we get too many cache misses.

**Comment by robdockins** [comment]
Regarding the strictness of `&&`: one of the goals of the new evalautor was to precisely implement the theoretical semantics.  The theoretical semantics indicates that `&&` is strict, and so the evaluator treats it so.  There are probably quite a few places where subtle strictness issues are now different.  Ideally, the behavior of the evaluator now matches what the domain semantics claims it should be; if not, I consider it a bug.

In this particular case, the short-cutting `/\` operator proposed in #326 is basically what you want instead, and is basically identical to the `if` expression you've written

**Comment by robdockins** [comment]
Some benchmarking revealed that the LRU strategy loses to an unbounded caching strategy in pretty much every case, and an adaptive strategy fares no better.

I've update the caching strategy to instead retain an unbounded history of elements for each sequence.  This has the potential to cause problems with retaining too much memory, but I've not observed it in practice.

With the update in dae3ab11b1c641491bb29c2eac58ee0d67b89b3b , the code above runs essentially instantly for up to maximum size `[0 .. 255]`
