### ISSUE TITLE
Concretely evaluate `random` during symbolic evaluation

### ISSUE THREAD

**Issue by acfoltzer** [GaloisInc/cryptol#364]
Right now the symbolic evaluator barfs on any call to `random`, but since `random` is deterministic given a seed, we should just concretely evaluate it as long as the seed is concrete. If the seed is symbolic, we should still give an error.

**Comment by yav** [comment]
Having `random` in a pure language is a bug I think, and it is odd to pretend that it is a pure function.

At best, I think we should think of `random` as `trace` in Haskell---it is not really a part of the language but, I guess, it is useful for testing/debugging.  So I am not sure that we need/want to support it in symbolic evaluation.

If we did though, it might be better to replace each call to `random` with a fresh symbolic variable.   This should simulate the behavior that we don't know what random will return which, I think, is the intention when using it.

**Comment by acfoltzer** [comment]
The current implementation of `random` is a pure function, since you have to fully specify a seed with each call. There's no state that gets reused between different invocations of random. So I think that for now, when we have a concrete seed, the right choice is to concretely evaluate it.

The really odd part of `random` is that it's not possible to symbolically simulate it when the seed is symbolic. We _could_ in theory support this by providing a Cryptol implementation of the MWC algorithm, but I think this would be a misplaced effort.

**Comment by TomMD** [comment]
> We could in theory support this by providing a Cryptol implementation of the MWC algorithm, but I think this would be a misplaced effort.

Actually, it would be ThreeFish a la tf-random.

**Comment by acfoltzer** [comment]
Right you are

**Comment by yav** [comment]
Even though `random` is supposed to be deterministic, I doubt that we want to be sensitive to which random number algorithm we are using.  For example, `random` currently uses the same function we are using for testing.  So, if we were to improve that, say to get better coverage, the results of random would also change.

**Comment by brianhuffman** [comment]
I agree with @yav on this point. It seems a bit nonsense to be able to prove something like `:prove random 0 == 0x8b`, especially if we are reserving the right to replace `random` with a different prng implementation in the future.

**Comment by robdockins** [comment]
The main impetus for this is that `random` is useful for generating a quantity of arbitrary data for testing and benchmarking purposes.  For a long time, the symbolic evaluator benchmarks were producing useless data because we were using `random` to select some arbitrary data, and the evaluator was failing immediately.  Because it was an automated benchmark task, nobody was looking at the output, so it went unnoticed for a long time.  The "fix" was to copy-and-paste the output of random into the file so it would actually do some work instead of just dying.

Now, I agree it is a bit strange to rely on the results of `random` in proofs and such, but if we are going to have it at all, I think it should compute whatever value it is going to compute in as many contexts as are reasonable.

**Comment by acfoltzer** [comment]
What about adding a hard-to-miss warning when symbolic execution gets to `random`? It could emphasize that its values could change depending on the underlying algorithm, and that it should only be used to generate arbitrary data for testing purposes.

**Comment by TomMD** [comment]
I like acfoltzer's solution here.  I just hit this issue once again in a situation I will now present in hopes it provides motivation.

I was asked if we could efficiently `:sat \h m -> f h m == h` (note the universal quantification).  The answer is "yes we can efficiently do that for the given `f`".  Then someone came back and asked "what about particular values of `h`?".  Now there's an interesting question. The issue is not `\exists m \exists h s.t. f h m == h` since I know that is for a fact true.  Rather, I want to know in practice if we fix h to an arbitrary constant can we get `m` efficiently.  Enter the small hiccup:

```
let h = random zero
:sat \m -> f h m == h
```

Which results in error. Instead I must copy and paste the value of `random zero`, yielding `h' == h` but with a special representation that can be simulated.

**Comment by robdockins** [comment]
The fix for this bug does not implement the warning discussed above.  If anyone has strong opinions about this, feel free to reopen the bug.
