### ISSUE TITLE
Symbolically executing some rotate operations takes exponential time

### ISSUE THREAD

**Issue by brianhuffman** [GaloisInc/cryptol#376]
Specifically, there seems to be a problem when the rotation amount is represented as a list of bits, and the rotated list is not a bitvector. For example:

```
:set prover=offline
:sat \a b c d e f g h i j k l m n o p -> [0..15] <<< [a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p] == [7..15]#[0..6]
```

On my machine, this example with a 16-bit rotation amount takes about 6 seconds, and the time approximately doubles with each additional bit. On the other hand, the size of the generated smtlib grows linearly with the number of bit arguments.

Also, the smtlib output starts by concatenating all the bits into a bitvector and then extracting each bit out again, which seems wasteful.

**Comment by robdockins** [comment]
Right now, the way these operations are implemented constructs an if/then/else tree based on the bits in the index; this tree has size `2^n` for `n` bits.  (<<) and (>>) are significantly faster because we get to collapse huge parts of the tree (shift indices larger than the size of the vector always give 0).

We might get some significant savings in this case if we first take the modulus of the index by `k` (where `k` is the length of the array being rotated) and only build the if/then/else tree up to depth `width k`.
