### ISSUE TITLE
Record updater 

### ISSUE THREAD

**Issue by jldodds** [GaloisInc/cryptol#399]
It would be convenient to have a record update expression, such as Haskell's:

```> data Foo = Foo { a :: Int, b :: Int, c :: String }  -- define a Foo
> let foo = Foo { a = 1, b = 2, c = "Hello" }         -- create a Foo
> let updateFoo x = x { c = "Goodbye" }               -- function to update Foos
> updateFoo foo                                       -- update the Foo
Foo {a = 1, b = 2, c = "Goodbye" }
```

**Comment by brianhuffman** [comment]
The syntax would have to be a bit different from Haskell, since `x {c = "Goodbye"}` would be ambiguous: Is this updating a record field of `x`, or applying function `x` to an argument of type `{c : String}`?

Perhaps something like `x {c := "Goodbye"}` would work.

**Comment by elliottt** [comment]
You could also do something like `{ x with c = "Goodbye" }`, like in ocaml and f#.

**Comment by weaversa** [comment]
I like Trevor's syntax best so far.

**Comment by yav** [comment]
What type would you like this to have?  A monomorphic update would be fairly easy, I think:

    set l :: Has l a t => a -> t -> t

However, an update function that allows for changing the type of the filed would be tricky to do.

**Comment by jldodds** [comment]
My needs are met by monomorphic update. I don't think it's unreasonable to ask the user to write their own function for an update that changes field types, since they probably won't do that too often.

**Comment by brianhuffman** [comment]
In a discussion with @robdockins a while back, another concern came up: nested record updates. We might like to have nice syntax for updating, say, field `x` of the nested record `r = {u = 0, v = {x = 3, y = 4}}`. With the Haskell-style proposals above, this would require mentioning `r` multiple times, like `r { v := r.v { x := 9 } }`.

**Comment by yav** [comment]
After thinking about this some more, here are some more notes:

1. It may be nicer if updating a field takes an expression with a free variable for the old value of a field, instead of an explicit function.   This would allow us to write things like `{ r | x -> x + 1 }`, instead of `{ r | x -> \x -> x + 1 }`

2. With nested updates, the order in which the updates are done might matter.  For example, consider `{ r | x = a, x.y = b }`.  The above definitions specify a strict order, so technically this is not a problem, but in practice it may lead to subtle errors, so we may want to give a warning if there are overlapping updates.  Alternatively, we could just treat that  as an error.

**Comment by brianhuffman** [comment]
@yav is this feature done? We should close this ticket once documentation and test cases are in place.

**Comment by yav** [comment]
I think so, there might even be documentation, but I should probably add some tests.  I've assigned it to myself.
