### ISSUE TITLE
Inequality constraints

### ISSUE THREAD

**Issue by msaaltink** [GaloisInc/cryptol#416]
Some partial type functions induce inequality constraints, for example, if a file contains

    g : {n} (fin n, 3 >= width n) => [lengthFromThenTo 1 n 7][3]
    g = [1, n .. 7]

on loading into the REPL we get this error

    [error] at ./test.cry:6:1--6:16:
      Failed to validate user-specified signature.
	In the definition of 'g', at ./test.cry:6:1--6:2:
	  for any type n
	    fin n
	    3 >= width n
	  =>
	  1 /= n
	    arising from
	    use of partial type function lengthFromThenTo
	    at ./test.cry:5:5--5:61

Unfortunately there does not seem to be any available syntax to add this constraint; changing the declaration of g to

    g : {n} (fin n, 3 >= width n, 1 /= n) => [lengthFromThenTo 1 n 7][3]

and reloading the file gives

    [error] (/=) 1 n is not a valid constraint
    [error] at ./test.cry:6:1--6:16 Type not in scope: (/=)

I have not seen anything in the manuals suggesting what to write for this constraint.

Changing the declaration of g to

    g: {n} (fin n, 3 >= width n) => [_][3]

avoiding any mention of lengthFromThenTo, works, a bit strangely:

    Main> :t g
    g : {n} (fin n, 3 >= width n) => [lengthFromThenTo 1 n 7][3]

The constraint has **not been added** to the inferred signature.  So now I can get a run-time type error:

    Main> g`{4}
    [0x1, 0x4, 0x7]
    Main> g`{1}

    type cannot be demoted: lengthFromThenTo 1 1 7
    Main> :t g`{1}
    g`{1} : [(error: Invalid applicatoin of lengthFromThenTo to 1 1 7)][3]

This error makes the reference evaluator exit the REPL:

    Main> :eval g`{4}
    [[False, False, True], [True, False, False], [True, True, True]]
    Main> :eval g`{1}
    cryptol: TypeCannotBeDemoted (TCon (TF TCLenFromThenTo) [TCon (TC (TCNum 1)) [],TCon (TC (TCNum 1)) [],TCon (TC (TCNum 7)) []])
    bash$

**Comment by msaaltink** [comment]
Also this is not good for the :prove command

    Main> :pro g`{1}@0 @0
    cryptol: You have encountered a bug in Cryptol's implementation.
    *** Please create an issue at https://github.com/galoisinc/cryptol/issues
    
    %< --------------------------------------------------- 
      Revision:  e23a8175cc87b832b84824f529dc8a50191df1ae
      Branch:    master (non-committed files present during build)
      Location:  [Eval] evalType
      Message:   Lingering typer error
                 (error: Invalid applicatoin of lengthFromThenTo to 1 1 7)
    %< ---------------------------------------------------

**Comment by brianhuffman** [comment]
Cryptol tries to maintain an invariant on type schemas that mention partial type functions: The constraints of the type schema must be sufficient to prove that all applications of partial type functions mentioned in the schema are well-defined. For example, Cryptol will disallow a declaration with the type signature `foo : {m, n} (fin m, fin n) => [m - n]` with an error message about being unable to prove `m >= n`.

However, this invariant is violated by the types of two primitives:
```
primitive fromThen : {first, next, bits, len}
                     ( fin first, fin next, fin bits
                     , bits >= width first, bits >= width next
                     , lengthFromThen first next bits == len) => [len][bits]

primitive fromThenTo : {first, next, last, a, len}
                       ( fin first, fin next, fin last
                       , Literal first a, Literal next a, Literal last a
                       , lengthFromThenTo first next last == len) => [len]a
```
Here, `lengthFromThen` and `lengthFromThenTo` are partial type functions that are undefined when their first two arguments are equal. However, the constraints in the signatures for those primitives do not rule out cases where `first` and `next` are equal, so the invariant is violated.

To fix this bug, we need to add `first /= next` constraints to the types of `fromThen` and `fromThenTo`. And in order to do that, we need to add concrete syntax for `m /= n` constraints. (I suppose we ought to use `m != n` instead, for consistency with Cryptol's value-level comparison operator.)
