### ISSUE TITLE
Picky with comment lines with more than one asterisk

### ISSUE THREAD

**Issue by benjaminjellison** [GaloisInc/cryptol#438]
Trying to write code with comment blocks led to some parse errors.  For example:

```
/** Test **/
/** Test **/
b x = 0
```

It appears you can't have two lines with block comments that have two or more asterisks unless you have code inbetween.  For example, this loads fine:
```
/** Test */
b x = 0
/** Test */
c x = 0
```

A comment block with two or more asterisks also can't end a program.  For example, this fails:
```
/** Test */
b x = 0
/** Test */
```

**Comment by brianhuffman** [comment]
In recent versions of Cryptol, a comment block starting with `/**` specifies the documentation string for the following top-level function declaration. The documentation is shown when you use the `:?` or `:help` REPL commands.

We should make sure that this feature is properly documented.

**Comment by jpziegler** [comment]
Sometimes people use lots of stars to emphasize comments, like so:
```
/***** ATTENTION *****/
/***** WARNING!! *****/
b x = 0
```
Which leads to the difficult-to-parse error:
```
Parse error at ./test.cry:3:1, unexpected b
```
I would think the behavior should be to accept all valid comments (such as all the examples given in this thread) quietly, plus generate documentation if the docstring format is met. (And skip it otherwise.)

**Comment by brianhuffman** [comment]
I started working on a patch to fix this, and it's surprisingly tricky to get the behavior we want. Currently, we drop all ordinary `/* */` comments from the token stream before the parser sees them, while doc-comments `/** **/` are preserved as special `DOC` tokens. This means they can only occur where there is an explicit `DOC` terminal in the grammar.

If we want to allow them to occur anywhere a normal comment could, then we have to do something completely different. The "Line Numbers" technique described in 2.5.3 of the happy manual is very close to what we need. Basically, we can add a new state component to the `Parser` monad of type `Maybe (Located String)` to keep track of the most-recently-read `DOC` token (if any). The `lexerP` function used to get the next token skips `DOC` tokens, so ordinary grammar productions can ignore them. In productions that consume a doc-string (e.g. top-level value declarations) we use a monadic parser action that retrieves the doc-string from the monad state.

This *almost* works perfectly. I still have a problem with doc-comments that occur at the end of a file, because the parser can't tell when the next token is the `EOF` marker if there is a `DOC` token in front of it.

**Comment by brianhuffman** [comment]
Changeset 79fbb61 makes it so that e.g. `/***** ATTENTION *****/` is parsed as an ordinary comment. For high-emphasis comments, you can just use 3 or more stars.

I talked with @yav about this, and we think that it's better not to implement the ignore-doc-strings-in-unexpected-places feature. We don't want to encourage anyone to use doc-string comments as high-emphasis comments, and anyway with the new patch it's easier to avoid accidental use of doc-strings.

**Comment by yav** [comment]
I made some changes to the parsing errors in 9de90e57528, hopefully they help in this case.

**Comment by WeeknightMVP** [comment]
I can think of other use cases where a developer might want the interpreter _or another tool_ to process docstrings:

```Haskell
  /** 
   * a parametrizable specification of the 
   * [Secure Hash Standard](https://csrc.nist.gov/publications/detail/fips/180/4/final) 
   */
  module SHA where 
    // ...
```

This could apply to an API document generator, or to a new feature for the interpreter's help system to describe a module that has been imported. 

```Haskell
  /** a base function for untruncated SHA-2 variants */
  SHA-2 :
    { /** bitlength of message to hash */ L}
    ((2 * w) >= (1 + (width L)), (8 * w) >= s) => 
    /** {@id msg} message to hash */ [L] -> /** digest of {@ref msg} */ [s]
```

This is further out, but could be one approach for the interpreter _or another tool_ to describe type parameters and the components of functions, tuples, or records in a symbol's type signature.

I think the C-style `/**` syntax introduces an expectation that docstrings are essentially comments, and overspecifying their placement and format inadvertently discourages potential adoption and growth of the software ecosystem for these tools.  Any developers that adopt Cryptol are probably doing so to verify crypto implementations written in C or Java, or they code in Haskell and are curious about functional programming for crypto.  In all of these languages, decoupled tools (e.g. Oxygen, Javadoc, and Haddock, respectively) can process docstrings annotated according to their respective needs, as enabled by _conventions_ rather than _restrictions_ on comment format and placement.  (Cryptol is more consistent with Python in this regard, but Python at least clearly distinguishes docstrings (`"""`) from comments (`#`).)

**Comment by WeeknightMVP** [comment]
I recently encountered another situation where rejecting an unexpected docstring was inconvenient: Cryptol embedded in SAWScript.  I wanted to `import "Extras.cry";`, but got an error message (reflecting an issue with the `Zero` typeclass that has since been corrected), so I just copied the functions I wanted, e.g.:

```Haskell
let main : TopLevel () = do {
  let {{
    /**
     * Logical negation
     */
    not : {a} (Logic a) => a -> a
    not a = ~ a
    
    /**
     * Conjunction
     */
    and : {n} (fin n) => [n]Bit -> Bit
    and xs = ~zero == xs
    
    /**
     * Disjunction
     */
    or : {n} (fin n) => [n]Bit -> Bit
    or xs = zero != xs
  }};
  
  print "Done!";
};
```

But this produced an error as well:

```
Parse error at ...\embedded_docstring_test.saw:3:5,
  unexpected: /**
     * Logical negation
     */
  expected: a declaration)
```

So I sighed and put a space between each asterisk pair and everything worked fine, but this is another case where not ignoring unexpected docstrings disrupts workflow.

**Comment by atomb** [comment]
The remainder of this is now in GaloisInc/saw-script#577.
