### ISSUE TITLE
Does not compile under Mint Linux

### ISSUE THREAD

**Issue by Johanvdberg** [GaloisInc/cryptol#460]
When compiling cryptol under Min Linux 18, I get the following error:

cabal install -j --only-dependencies 
Resolving dependencies...
cabal: Could not resolve dependencies:
trying: random-1.1/installed-c46... (user goal)
next goal: cryptol (user goal)
rejecting: cryptol-2.5.0 (conflict: random => time==1.5.0.1/installed-1b9...,
cryptol => time>=1.6.0.1)
rejecting: cryptol-2.4.0, 2.3.0, 2.2.6, 2.2.5, 2.2.4, 2.2.3, 2.2.2, 2.2.1,
2.2.0 (global constraint requires ==2.5.0)
Dependency tree exhaustively searched.

Note: when using a sandbox, all packages are required to have consistent
dependencies. Try reinstalling/unregistering the offending packages or
recreating the sandbox.
Makefile:149: recipe for target 'dist/setup-config' failed
make: *** [dist/setup-config] Error 1

**Comment by yav** [comment]
Hello,

the conflict is likely caused because Mint comes with a slightly older version of GHC and libraries than what Cryptol expects.   In particular, it looks like Mint 18 (Sarah) comes with GHC 7.10, and I believe we currently expect at least GHC 8.

I'll leave this ticket open, as we should probably try to spot such situations and report a more meaningful error message.

**Comment by Johanvdberg** [comment]
Current version 'The Glorious Glasgow Haskell Compilation System, version 7.10.3'

What will be the best route to update GHC?  For example installing it in my home directory.

**Comment by yav** [comment]
Opinions on the best route differ, but what I personally tend to do is download a GHC and cabal binaries and put them somewhere in my home directory, modifying the path as necessary.

GHC binaries: https://www.haskell.org/ghc/download_ghc_8_2_1.html#binaries
cabal binaries: https://www.haskell.org/cabal/download.html

`cabal-install` provides a command-line tool called `cabal`, which makes it easy to download and install Haskell libraries from http://hackage.haskell.org/, which is the main public resource for sharing Haskell libraries.

I think that should be all.  It's been a while since I've had to setup a Haskell environment from scratch, so please feel free to post another message here, if something didn't work as expected.

**Comment by Johanvdberg** [comment]
in the repository root:

cabal-install version 2.0.0.0
compiled using version 2.0.0.2 of the Cabal library 

The Glorious Glasgow Haskell Compilation System, version 8.2.1


running make, I get the following error

cabal install -j --only-dependencies 
Resolving dependencies...
Notice: installing into a sandbox located at
/home/johan/git/cryptol/.cabal-sandbox
Configuring sbv-7.3...
Building sbv-7.3...
Failed to install sbv-7.3
Build log ( /home/johan/git/cryptol/.cabal-sandbox/logs/ghc-8.2.1/sbv-7.3-9TxzYQvebLZI3wS7UzYUG5.log ):
cabal: Entering directory '/tmp/cabal-tmp-3325/sbv-7.3'
Configuring sbv-7.3...
Preprocessing library for sbv-7.3..
Building library for sbv-7.3..
[ 1 of 90] Compiling Data.SBV.Control.Types ( Data/SBV/Control/Types.hs, dist/dist-sandbox-a9a46b47/build/Data/SBV/Control/Types.o )
<command line>: can't load .so/.DLL for: libtinfo.so (libtinfo.so: cannot open shared object file: No such file or directory)
cabal: Leaving directory '/tmp/cabal-tmp-3325/sbv-7.3'
cabal: Error: some packages failed to install:
sbv-7.3-9TxzYQvebLZI3wS7UzYUG5 failed during the building phase. The exception
was:
ExitFailure 1
Makefile:149: recipe for target 'dist/setup-config' failed
make: *** [dist/setup-config] Error 1

**Comment by yav** [comment]
Sounds like this got resolved, so I'll close it for now.
