### ISSUE TITLE
Weird Defaulting on Padding

### ISSUE THREAD

**Issue by tmmcafe** [GaloisInc/cryptol#476]
I realize this isn't the best way to write padding functions, but I found that when I wrote my code this way I got really unexpected behavior.  Here's my function:

```
pad64 : {n, m} (fin n, fin m, n <= m, m <= n + 63, m%64 == 0) => [n] -> [m]
pad64 x = x # 0
```

Here's what I get when I run it:

```
Main> pad64 3
Assuming a = 494079
Assuming b = 494080
6
```

Somehow it defaults 3 to 494079 bits.

I ran this on '''942173b''', the build from 10/18.  I'm not worried about this example (rewriting it with '''%^''' works fine) but I wanted to make sure it wasn't some deeper problem.

**Comment by yav** [comment]
There's no deep problem here, although we may want to do something more sensible.   The issue is that you are asking to pad something to a multiple of 64 but you didn't say how big you'd like the result to be.  So, Cryptol just picked something that would work---the actual number is an artifact of the algorithm used by the SMT solver.

I guess one thing we could do was to look for some kind of "small" (for a given definition of "small") instantiation, as this might be what's desirable at the REPL
