### ISSUE TITLE
Curry–Howard correspondence and cryptol

### ISSUE THREAD

**Issue by Johanvdberg** [GaloisInc/cryptol#478]
Not knowing much about "Curry–Howard correspondence"

What is the corresponding logic that is related to cryptol?

Alternatively: Is cryptol a sub-langauge of some other functional language?

I asked since I just learned that typed lambda calculus does not suffer from all the problem that untyped lambda calculus suffer from, eg halting problem.

**Comment by brianhuffman** [comment]
Because Cryptol has `error` and unrestricted recursion, every type is inhabited. This corresponds to a logic where every proposition is provable, i.e. the corresponding logic is inconsistent.

If we pretended that Cryptol didn't have error values or unrestricted recursion, then maybe its corresponding logic would be a bit more interesting. I'll need to think about it.

**Comment by Johanvdberg** [comment]
A bit more general, is it common that a functional language does map to a logic?

When motivating that a functional language create well behaved program, how import is a mapping to a logic that is decidable?
