### ISSUE TITLE
Slow Counterexample Detection for Seemingly Obvious Non-Theorem

### ISSUE THREAD

**Issue by dmzimmerman** [GaloisInc/cryptol#500]
When demonstrating Cryptol, I wanted an example of an obvious non-theorem about AES: the plaintext and ciphertext are always equivalent (in the attached file, this is called `crazy_prop`). Because nearly every point in the state space is a counterexample, `:check crazy_prop` returns instantly... but `:prove crazy_prop` takes 1 day, 21 hours plus (on my particular MacBook Pro, with Cryptol 2.5.0 (ff86d02600ce65eed00e2e4c7db5f34b93b52eeb) and Z3 4.6.0) to return False with a counterexample, and `:sat crazy_prop` exhibits similar behavior. This seems like an excessive amount of time.

It may be the case that this is the best the solver can do when handed such an eminently disprovable property to prove... but it might be reasonable from a Cryptol UX standpoint to do a quick `:check` pass before handing properties off to a solver - or to do a `:check` pass asynchronously if a solver takes more than a threshold amount of time - in order to short-circuit such long solver executions and return negative results more quickly.
[AES128.cry.zip](https://github.com/GaloisInc/cryptol/files/1804020/AES128.cry.zip)

**Comment by jpziegler** [comment]
Happy 500th issue! Love this one.

If `:sat crazy_prop` finds a solution, I'd love to see it!

How about adding `:exhaust` to `:set prover=any`? (Or, as suggested, as a fallback/companion for any proof attempt.) Could make it an option: `:set test-properties=true`.

Interestingly, `abc` quickly found a counterexample: The zero-vector.

**Comment by brianhuffman** [comment]
Z3 is pretty bad on this problem even when you fix nearly all of the bits to concrete values:
```
AES128> :prove \(x:[2]) -> crazy_prop 0 (0#x)
(\(x : [2]) -> crazy_prop 0 (0 # x)) 0x1 = False
(Total Elapsed Time: 43.607s, using Z3)
```

**Comment by weaversa** [comment]
The deadline for submitting benchmarks and solvers to the SAT’18 competition is Saturday March 31, 2018 (23:59 GMT -12, anywhere on earth). Visit the competition website sat2018.forsyte.tuwien.ac.at <http://sat2018.forsyte.tuwien.ac.at/> for details.

I think this would be a good candidate.

**Comment by atomb** [comment]
One downside of always running `:check` is that, although it's faster in this case, in some cases it can be dramatically slower than `:prove`. Having it available as an option, though, is probably reasonable (and optionally adding `:exhaust` to `prover=any` seems reasonable, too).

And thanks for the reminder about SAT'18, @weaversa!

**Comment by jpziegler** [comment]
Perhaps, rather than (or in addition to) the current separate `:exhaust` command, we should simply add `:set prover=exhaust`. Then it would automatically be included in `:set prover=any`. The advantage of this approach is that when a user chooses `:set prover=any`, they're definitely expecting to spawn a lot of wasteful/redundant processes, so adding `exhaust` to the mix probably won't annoy people too much.
Everybody seems to have all those extra cores lying around, after all.

Of course, that change alone won't fix the real issue: Running a single/default prover and missing low-hanging fruit that could easily be caught by a few random test vectors. In the single prover case, I suppose the user may not want extra processes eating up CPU/memory (even if it's the original Cryptol instance). But expecting the user to set some specific option requires insight into the problem, which seems a silly thing to require in this case since, again, this is low-hanging fruit.

This is an opportunity to make things more push-button, at least for some classes or problems. Is there a sensible way to do it? And are there enough such problems to make it worthwhile? Or should we simply leave it to the SMT solver developers to decide if some random testing is worthwhile.

**Comment by LeventErkok** [comment]
I'm not sure if this applies to cryptol-2; but back in the days of cryptol-1, we used to automatically "quick-check" properties upon any load. (There was a way to turn it off, but the default was to perform the quick-check.)

The idea behind this was to precisely catch things like this: Obviously wrong properties get flagged at load time. I'm not sure how it would've worked in this scenario, but I'm guessing Cryptol no longer does this?

**Comment by brianhuffman** [comment]
This is not in scope for Cryptol; it's a z3 problem.
