### ISSUE TITLE
Possible memory leak in SBV: Might possibly impact Cryptol performance too

### ISSUE THREAD

**Issue by LeventErkok** [GaloisInc/cryptol#514]
I've run into a very curious memory-leak issue in SBV: https://github.com/LeventErkok/sbv/issues/396

Now, this is not a Cryptol issue obviously; but I'm pretty sure I can write a Cryptol program and make it go crazy by generating similar SBV code. I've spent some time analyzing it, but alas I've run out of ideas to try.

If you guys can spare some cycles to debug, I'd be much appreciative. Otherwise, I'll write that very program in Cryptol and complain that it's blowing up and file a proper ticket! :-)

(Of course, It is possible that this is already happening with your examples and you just haven't realized yet and attributed it to other issues.)

Joking aside, it'd be good if some Galois experts can opine on the issue. Much appreciated. Even replicating on your side and confirming what I see in my environment would be valuable.

**Comment by brianhuffman** [comment]
I ported the Haskell SBV example to Cryptol here:
```
type Color = [2]

Black = 0 : Color
Blue  = 1 : Color
Green = 2 : Color
Red   = 3 : Color

// Use 8-bit words for button numbers, even though we only have 1 to 19.
type Button = [8]

// The grid is an array mapping each button to its color.
type Grid = [20]Color

// Given a button press, and the current grid, compute the next grid.
// If the button is "unpressable", i.e., if it is not one of the center
// buttons or it is currently colored black, we return the grid unchanged.
next : Button -> Grid -> Grid
next b g =
  if g@b == Black then g else
  if b ==  5 then rot [ 1,  2,  6, 10,  9,  4] else
  if b ==  6 then rot [ 2,  3,  7, 11, 10,  5] else
  if b ==  9 then rot [ 4,  5, 10, 14, 13,  8] else
  if b == 10 then rot [ 5,  6, 11, 15, 14,  9] else
  if b == 11 then rot [ 6,  7, 12, 16, 15, 10] else
  if b == 14 then rot [ 9, 10, 15, 18, 17, 13] else
  if b == 15 then rot [10, 11, 16, 19, 18, 14] else g
  where rot xs = updates g (xs <<< 1) (g @@ xs)

hexSearch : {depth} (fin depth) => [depth]Button -> Bit
hexSearch bs = foldr next initBoard bs == finalBoard

initBoard : Grid
initBoard = [0, Black, Black, Black, Red, Blue, Green, Red, Black, Green, Green, Green, Black, Red, Green, Green, Red, Black, Black, Black]

finalBoard : Grid
finalBoard = [0, Black, Red, Black, Black, Green, Green, Black, Red, Green, Blue, Green, Red, Black, Green, Green, Black, Black, Red, Black]
```
Now we test with some example sizes:
```
Main> :sat hexSearch`{2}
Unsatisfiable
(Total Elapsed Time: 0.027s, using Z3)
Main> :sat hexSearch`{3}
Unsatisfiable
(Total Elapsed Time: 0.048s, using Z3)
Main> :sat hexSearch`{4}
Unsatisfiable
(Total Elapsed Time: 0.156s, using Z3)
Main> :sat hexSearch`{5}
Unsatisfiable
(Total Elapsed Time: 1.171s, using Z3)
Main> :sat hexSearch`{6}
hexSearch`{6} [0x06, 0x0e, 0x09, 0x0b, 0x0a, 0x0a] = True
(Total Elapsed Time: 11.726s, using Z3)
```
At this point, the memory usage for the cryptol process is at 1.36 GB.
```
hexSearch`{7} [0x02, 0x06, 0x0e, 0x09, 0x0b, 0x0a, 0x0a] = True
(Total Elapsed Time: 2m:44.995s, using Z3)
```
Now the memory usage for cryptol is up to 8.32 GB (!).

Also it appears that the cryptol process (rather than z3) is using all of the CPU for almost the entire time. I'll look into it.

**Comment by brianhuffman** [comment]
If I change the definition of the local function `rot` from
```
    rot xs = updates g (xs <<< 1) (g @@ xs)
```
to
```
    rot xs = g @@ (updates [0..19] (xs <<< 1) xs)
```
then it gets a lot faster.
```
Main> :sat hexSearch`{10}
hexSearch`{10}
  [0x05, 0x0f, 0x06, 0x0e, 0x0b, 0x09, 0x0e, 0x0e, 0x0f, 0x05] = True
(Total Elapsed Time: 4.958s, using Z3)
Main> :sat hexSearch`{10}
hexSearch`{10}
  [0x05, 0x0f, 0x06, 0x0e, 0x0b, 0x09, 0x0e, 0x0e, 0x0f, 0x05] = True
(Total Elapsed Time: 4.830s, using Z3)
Main> :sat hexSearch`{11}
hexSearch`{11}
  [0x0e, 0x0b, 0x02, 0x0a, 0x06, 0x09, 0x06, 0x06, 0x06, 0x06,
   0x06] = True
(Total Elapsed Time: 16.223s, using Z3)
Main> :sat hexSearch`{12}
hexSearch`{12}
  [0x05, 0x05, 0x05, 0x05, 0x0e, 0x06, 0x0b, 0x05, 0x05, 0x0a, 0x10,
   0x09] = True
(Total Elapsed Time: 26.940s, using Z3)
Main> :sat hexSearch`{13}
hexSearch`{13}
  [0x0f, 0x0b, 0x02, 0x05, 0x06, 0x09, 0x0e, 0x0b, 0x09, 0x05, 0x07,
   0x0f, 0x0a] = True
(Total Elapsed Time: 1m:18.766s, using Z3)
```
But it looks like the time behavior is still exponential; it just has a smaller exponent. Also the runtime is still dominated by the cryptol process rather than z3.

Here's what I think is happening. This program basically has the same structure as a barrel-shifter circuit: There are several layers of symbolic muxes, each of which selects between different permutations of the input variables. The circuit size (as a dag) is linear in the number of layers, but exponential when expanded into a tree. It looks like we're losing sharing somewhere, and then rediscovering the shared subterms later. The alternative definition of `rot` just reduces the number of muxes per layer, which is why it blows up at a slower rate.

**Comment by brianhuffman** [comment]
Update: I tried running the same example in saw, and I can do ``hexSearch`{30}`` in 16 seconds total time with less than 100 MB of memory used. The time is about the same with either definition of `rot`.

Now I'm guessing that the implementation of the `update` primitive is different in saw vs cryptol, and maybe this is the source of the problem. I'll have a closer look tomorrow.

**Comment by brianhuffman** [comment]
It turns out the problem was not specifically related to `update`, but rather to symbolic if-then-else on non-bitvector sequence types (even stupidly small ones like `[1]()`). For example, the following example previously took several seconds to run (exponential in the length of `bs`) but as of 99773d7 it finishes almost instantly even for much larger sizes.
```
:prove \(bs:[28]) -> foldr (\b x -> if b then x else x) zero bs == (zero:[1]())
```

**Comment by LeventErkok** [comment]
@brianhuffman This is pretty cool; alas doesn't help with SBV.. In the SBV case, it comes down to this line:

https://github.com/LeventErkok/sbv/blob/master/Data/SBV/Core/Model.hs#L1537

When the "arrays" are merged the sharing gets lost inside the chain of `ite` calls, only to be reconstructed later.

I'm thinking `SFunArray` needs to not use functions, but something better; perhaps an association list. Any ideas are most welcome!
