### ISSUE TITLE
Unexpected defaulting warning in code with a type error

### ISSUE THREAD

**Issue by brianhuffman** [GaloisInc/cryptol#525]
I came across this example while updating the "Programming Cryptol" book. An exercise asks the reader to try `split` with an incorrect type:
```
Cryptol> split [1..12] : [5][2][8]
[warning] at <interactive>:1:7--1:14:
  Defaulting type argument 'a' of 'fromTo' to [4]

[error] at <interactive>:1:7--1:14:
  Type mismatch:
    Expected type: 10
    Inferred type: 12
```
Why is there a defaulting warning? The sizes on the type annotation may be wrong, but the element type `[8]` is fine; why do we bother defaulting the element type to `[4]` before reporting an error?

**Comment by yav** [comment]
I think that there are two things going on here:
   1. the reason `a` does not get to be `[8]` is that we don't unify types partially:  if we don't find a unifier we record an error, and we leaves the types as they were.   As a result `a` never gets instantiated.   I guess we could change `mgu` to always return a "best effort" substitution even when it fails.
   2. we don't stop type-checking when an error occurs, instead we record it and keep going in the hope of finding additional errors.  This is why we see the defaulting warning.  Some possible solutions:
       1. Stop after the first error
       2. Stop doing defaulting if we know that the program has errors
       3. Leave the algorithm as it, but don't show the defaulting warnings if there are errors.

Option 3 seems a bit iffy, but I think it might be OK because I don't think defaulted things should cause any errors---my thinking is that since they had to be defaulted, there was nothing else that could have forced their type.

Thoughts?

**Comment by brianhuffman** [comment]
I think that if we made `mgu` always return a "best effort" substitution, that would produce a result that is most like what I would expect.

So, for example if you type `[1..10]:[6][8]`, then `mgu` would be called on `[10]?a` and `[6][8]`, and `mgu` would return the substitution `?a = [8]` and the mismatch error `10 != 6`.
