### ISSUE TITLE
ABC giving incorrect result

### ISSUE THREAD

**Issue by weaversa** [GaloisInc/cryptol#558]
```
Cryptol> :sat \(x:[32]) -> x < 10
(\(x : [32]) -> x < 10) 376139263 = True
(Total Elapsed Time: 0.037s, using ABC)
Cryptol> it.arg1 < 10
False
```

**Comment by weaversa** [comment]
```
Cryptol> :sat \(x:[32]) -> (x!28 == False)
(\(x : [32]) -> (x ! 28 == False)) 268435456 = True
(Total Elapsed Time: 0.034s, using ABC)
Cryptol> it.arg1!28
True
```

I think the errors have to do with `abc` returning the wrong result when formulas are sufficiently simple. The command issued by SBV is `abc -S %blast; &sweep -C 5000; &syn4; &cec -s -m -C 2000` and I wonder if `%blast` or `&sweep` are solving the simple problems and the counter example is not being propagated correctly after the (presumably empty) `&cec` call.

**Comment by atomb** [comment]
I believe you're right about it being due to sufficiently simple problems. When I run ABC on the generated SMT-Lib file on the command line, and without the `-s` flag to `&cec`, ABC prints `Networks are NOT EQUIVALENT. Output 0 trivially differs (PI vs. constant).` without a specific model. And this happens even if I remove the `&sweep` and `&syn4` commands. To get it to really work properly, this will probably have to be fixed in ABC, but we can probably update SBV to be noisier about the fact that it didn't get a model.

**Comment by LeventErkok** [comment]
I intend to write a model-validator for SBV, though I'm not sure about the timeline. The idea is to make sure the counter-example is indeed valid, and throw an error if not. (Probably will be tied to an opt-in config varaible to avoid performance penalty.) I think it would be even easier for Cryptol to do so, since it has fewer operations to worry about, no universals, uninterpreted-functions etc.; that I'll have to somehow manage in SBV. (Most likely by tacitly accepting the model whenever there's something too complicated like that.)

But if someone does implement it for SBV and send a pull request, that'd be awesome as well!

Also note that you can call `z3` with the `model_validate=true` parameter; which does something similar. (It is also "best effort," I've seen cases where it produces an incorrect model, but the above parameter doesn't catch it.) Maybe you guys should turn that on via `SBV_Z3_OPTIONS` environment variable passing it via a Cryptol setting. Of course this only applies to z3, but might be worth it in really high-assurance use cases!

**Comment by LeventErkok** [comment]
Technology preview :-)

Here's the SBV equivalent:

```haskell
Prelude Data.SBV> satWith abc $ \x -> x .< (10::SWord32)
Satisfiable. Model:
  s0 = 376139263 :: Word32
```

And after SBV 8.1 is released (should happen sometime this weekend), you'll be able to say:

```haskell
Prelude Data.SBV> satWith abc{validateModel = True} $ \x -> x .< (10::SWord32)
*** Data.SBV: Model validation failure: Final output evaluated to False.
***
*** Environment:
***
***       s0 = 376139263 :: Word32
***
*** Backend solver returned a model that does not satisfy the constraints.
*** This could indicate a bug in the backend solver, or SBV itself. Please report.
***
*** Alleged model:
***
*** Satisfiable. Model:
***   s0 = 376139263 :: Word32
```

Should be trivial to port to Cryptol!

**Comment by LeventErkok** [comment]
@weaversa @atomb @brianhuffman @yav 

If you pull https://github.com/GaloisInc/cryptol/pull/580 and compile Cryptol, you can now say:

```
Cryptol> :set prover=abc
Cryptol> :sat \(x:[32]) -> x < 10
(\(x : [32]) -> x < 10) 0x166b6dff = True
(Total Elapsed Time: 0.076s, using ABC)
Cryptol> :set prover-validate=on
Cryptol> :sat \(x:[32]) -> x < 10
*** Data.SBV: Model validation failure: Final output evaluated to False.
***
*** Environment:
***
***       s0 = 376139263 :: Word32
***
*** Backend solver returned a model that does not satisfy the constraints.
*** This could indicate a bug in the backend solver, or SBV itself. Please report.
***
*** Alleged model:
***
*** Solution #1:
***   s0 = 376139263 :: Word32
(Total Elapsed Time: 0.075s, using ABC)
```

Of course this looks over the more interesting subject matter of validating proofs, but that's a much more difficult problem to tackle. But a worthy one indeed!
