### ISSUE TITLE
:prove shows the wrong elapsed time

### ISSUE THREAD

**Issue by brianhuffman** [GaloisInc/cryptol#572]
Run cryptol and tell it to prove a difficult property. It will say that the elapsed time is very quick (< 0.01s) when it has actually taken several seconds.
```
$ time cryptol -c ":prove \(x:[24]) -> x ! 0 ==> x * (x ^^ (-1)) == 1"
Loading module Cryptol
Q.E.D.
(Total Elapsed Time: 0.009s, using Z3)

real	0m7.193s
user	0m5.869s
sys	0m1.323s
```

**Comment by brianhuffman** [comment]
@yav and I discovered that with `:set debug` enabled, it prints both the correct time *and* an incorrect time:
```
Loading module Cryptol
Cryptol> :set debug=yes, please
Cryptol> :prove \(x:[24]) -> x!0 ==> x * (x ^^ (-1)) == 1
Simulating...
Trying proof with Z3
** Calling: z3 -nw -in -smt2
[...]
[SEND] (check-sat)
[RECV] unsat
*** Solver   : Z3
*** Exit code: ExitSuccess
Got result from Z3, time: 6.992s
Q.E.D.
(Total Elapsed Time: 0.011s, using Z3)
```

**Comment by LeventErkok** [comment]
This is definitely an SBV bug. Once we moved to the "Query" mode of doing things, the old way of measuring time just simply doesn't work. Sigh. I'll see if I can fix it.

**Comment by LeventErkok** [comment]
@brianhuffman @yav 

Just pushed a commit to SBV: https://github.com/LeventErkok/sbv/commit/6dc6599746efb9ae99f049076026a170445f1853

That should fix this issue, without you guys needing to work around it.

I'd appreciate if you can give it a quick try and let me know.

(If you pull from master and build, you'll probably have a minor compile breakage due to SBV's `AllSat` return value slightly changing; you can ignore the extra boolean result in there safely for Cryptol purposes. Let me know if it gives you hard time.)
