### ISSUE TITLE
Travis builds are failing

### ISSUE THREAD

**Issue by brianhuffman** [GaloisInc/cryptol#643]
Recent builds on https://travis-ci.org/GaloisInc/cryptol are failing for a bogus reason, possibly  having to do with `cabal` versions?
```
$ bash cry test
Running tests
cabal: unrecognized 'v2-install' option `--symlink-bindir=bin'
cry: line 72: bin/test-runner: No such file or directory
The command "bash cry test" exited with 127.
```

**Comment by atomb** [comment]
It looks as though `cabal-install` 3.0 changed its command-line flags somewhat, so there's no incantation that will work with both 2.4 and 3.0. That's frustrating. The Linux builds on Travis specify the version of `cabal-install` to use, but the macOS builds just use the latest in Homebrew. I wish there was a better way of constraining versions on macOS. We might consider removing it from the Travis builds, given how non-reproducible it is due to Homebrew dependencies.

**Comment by brianhuffman** [comment]
Recent Travis builds are working again, e.g. revision 42ab1ea48c90121b27e7092d16544cee5f27e324 https://travis-ci.org/GaloisInc/cryptol/builds/604148914
