### ISSUE TITLE
Inconsistent style across :set option names

### ISSUE THREAD

**Issue by brianhuffman** [GaloisInc/cryptol#656]
Here are the names of all the settable options in the Cryptol REPL, as shown by tab completion:
```
Cryptol> :set
ascii            debug            prover           satNum           tc-debug         warnDefaulting
base             infLength        prover-stats     show-examples    tc-solver        warnShadowing
core-lint        mono-binds       prover-validate  smtfile          tests
```
Some are hyphenated, and some use camelCase. We should choose a single convention and use it consistently.

**Comment by robdockins** [comment]
This has bothered me several times now since this ticket was filed.

I suggest we choose a convention and switch to it for the release following 2.10.  In addition, let's allow settings to be changed by the old names for at least one release (and issue a warning that the old names are deprecated), but not show the alternate names in documentation, etc.

I suggest we go with camel case, as it fits more nicely with idiomatic cryptol naming, as `-` is not a valid identifier character.
