### ISSUE TITLE
Better pretty printing of infix type operators with default fixity

### ISSUE THREAD

**Issue by yav** [GaloisInc/cryptol#670]
Here is an example:
```
type x +++ y = x-y
  
g : [6 +++ 2 +++ 1]
g = 2
```
If we ask for the type of `g` we get this:
```
Main> :t g
g : [(+++) ((+++) 6 2) 1]
```
In contrast, if we add and explicit fixity declaration, for example, `infixl 5 +++` , then we get a much nicer looking type:
```
Main> :t g
g : [6 +++ 2 +++ 1]
```

**Comment by brianhuffman** [comment]
A nice solution might be that if we don't declare a fixity for an infix operator, we can just always parenthesize every use of it when we print it.

Similarly, we should probably require disambiguating parentheses when parsing any infix operator without a fixity. In particular, `6 +++ 2 +++ 1` should probably be a fixity error upon parsing, because the user didn't specify either left- or right-associativity.

**Comment by yav** [comment]
I think the current default is that if you don't specify it explicitly it is left-associative.  Are you saying we should make the default non-associative?   Or just reject uses of operators unless there is an explicit fixity declaration?

I don't have a strong opinion, but I think we should probably do the same thing at the value and type.
If we require fixities to be always explicit we may have to allow local fixity declarations too (I am not sure if allow them at the moment).

**Comment by brianhuffman** [comment]
I think defaulting to non-associative would make the most sense. (Haskell doesn't do that, but they don't have non-associative operators at all; they probably would if they did.)
