### ISSUE TITLE
Symbolic Execution and undefined behaviour causes :sat and :prove to give wrong answers

### ISSUE THREAD

**Issue by weaversa** [GaloisInc/cryptol#70]
I can only guess that the symbolic execution engine is adding constraints that say "produce 0" for undefined behaviour such as divide by 0 and index out of bounds. Here are two strange test cases:

Cryptol> :sat (x:[4]) -> x/0 == 0
((x : [4]) -> x / 0 == 0) 0 = True
Cryptol> 0/0
division by 0

Cryptol> :sat (x:[4]) -> [1, 2, 3, 4]@x == 0
((x : [4]) -> [1, 2, 3, 4] @ x == 0) 6 = True
Cryptol> ((x : [4]) -> [1, 2, 3, 4] @ x == 0) 6
invalid sequence index: 6

The previous version of Cryptol also produces answers, but is very verbose about detecting 'safety violations'. I suggest adding something similar to the current version, as well as resurecting the old :safe command.

Cryptol> :sat \x -> (x:[4])/0 == 0
(\x -> (x:[4]) /0 == 0) 0x0
     = "command line", line 1, col 16: divide by zero
*\* A safety violation was detected, use the ":safe" command to check for others.
**\* ALERT: Run result does not match formal analysis.
**\*        This can be caused by strict safety semantics, showing up in
**\*        C and hardware translations.
**\*        Use :safe command to identify others

Cryptol> :sat \x -> [1 2 3 4]@(x:[4]) == 0
(\x -> [1 2 3 4]@(x:[4]) == 0) 0x4
     = "command line", line 1, col 17: index of 4 is out of bounds
(valid range is 0 thru 3).
*\* A safety violation was detected, use the ":safe" command to check for others.
**\* ALERT: Run result does not match formal analysis.
**\*        This can be caused by strict safety semantics, showing up in
**\*        C and hardware translations.
**\*        Use :safe command to identify others

**Comment by TomMD** [comment]
This appears to have fallen off the radar again.  @brianhuffman current thoughts?

(I ask because my foolish bug on an otherwise quick [tantrix](https://twitter.com/ID_AA_Carmack/status/680569924931063808) cryptol solution was made more opaque by this issue)

**Comment by dylanmc** [comment]
Not off the radar, rather "on the roadmap." I predict 2016 will lay the foundations  for fixing this, and also see the fix as well.

**Comment by brianhuffman** [comment]
My thoughts on this issue are unchanged since my comments from Nov 19 last year. We certainly don't want to accept "proofs" of programs that raise exceptions, but to implement this correctly we need to specify the strictness properties of all Cryptol language constructs. We'll also need to document the strictness semantics of SBV's assertion mechanism to see how we can use it.

**Comment by LeventErkok** [comment]
Just some thoughts.. It's really tricky to have the exception semantics "precisely" captured in symbolic execution: What if you have an if-then-else with one branch no exceptions and the other does? The issue is you don't know how to symbolically merge the two in general: Though you can go a long way before it becomes a real issue, the situation is just not clean.

In the mean time, I came to the rather humble conclusion that ":prove" should simply be a partial correctness proof: If it says yes, then the property is correct assuming there're no exceptions raised.

Then, a separate proof is run to find out if there are any such exceptions.

This keeps a clean separation of these two separate goals, and simplifies life.

This is what the Cryptol-1 implementation attempted in the SBV backend: There was a ":prove"/":sat" call; but also a separate ":safe" call.

I'd recommend Cryptol-2 adopting the same mechanism and keeping these two separate. Trying to do both at the same time ends up being a never ending fight with all sorts of weird behavior. Of course, if you want you can hook-up ":prove" to do both, in two different passes. The point is that you keep the two goals separately and attack them separately as well. There's a lot of code in Cryptol-1's SBV backend that keeps track of these "proof conditions" etc.; but it was never fully polished..

**Comment by dylanmc** [comment]
Brian will check out SBV's new features here, to determine whether it's "low hanging fruit" or not.
