### ISSUE TITLE
Superclass inference

### ISSUE THREAD

**Issue by robdockins** [GaloisInc/cryptol#738]
With a deeper typeclass hierarchy, it becomes more urgent that we implement super/subclass relationships.  This will make it so we can write just `Field a` instead of `Field a, Ring a, Zero a`, etc. in constraints.

By analogy to Haskell syntax, I think we should have the following superclass relationships.

```
class Zero a => Ring a
class Zero a => Logic a
class Ring a => Field a
class Ring a => Integral a
class (Field a, Cmp a) => Round a
class Eq a => Cmp a
class Eq a => SignedCmp a
```

**Comment by yav** [comment]
This shouldn't be too hard to hard to do.  There are two things we need to change:
  1. augment the signature checking code with a new "strategy" that will prove things by looking at super-classes (e.g., if we know `Ring`, we can prove `Zero`)
   2. the type inference code, so that we don't infer constraints that are sub-classes of each other.

Strictly speaking, things will work without (2), but it will help to infer nicer types, and also might help with defaulting.

The best place to hook in the code for (1) is probably in `proveImplication` in `Cryptol.TypeCheck.Solve`: we can just filter out goals that are reachable via superclass from the assumptions.

A good place to implement (2) might be in `insertGoal` in `Cryptol.TypeCheck.InferType`.  So whenever we add a new goal we check:
   1. Is it already implied via super class by an existing one?  If so, then don't add it, otherwise:
   2. Add it, and remove any existing goals that are implied by it via super class.
  (that's similar to what we do with `Literal` constraints)

We could change the representation of `Goals` to make these operations faster, but I'd start with a naive version, as I don't think we collect *that* many class constraints anyway...
