### ISSUE TITLE
Z3 vs z3

### ISSUE THREAD

**Issue by weaversa** [GaloisInc/cryptol#752]
```
$ cryptol
┏━╸┏━┓╻ ╻┏━┓╺┳╸┏━┓╻  
┃  ┣┳┛┗┳┛┣━┛ ┃ ┃ ┃┃  
┗━╸╹┗╸ ╹ ╹   ╹ ┗━┛┗━╸
version 2.8.1 (e914cef)
https://cryptol.net  :? for help

Loading module Cryptol
Cryptol> :prove True
Q.E.D.
(Total Elapsed Time: 0.007s, using "Z3")
Cryptol> :s prover=Z3
Prover must be cvc4, yices, z3, boolector, mathsat, abc, offline, any, sbv-cvc4, sbv-yices, sbv-z3, sbv-boolector, sbv-mathsat, sbv-abc, sbv-offline, sbv-any, w4-cvc4, w4-yices, w4-z3, w4-boolector, or w4-offline
```

**Comment by brianhuffman** [comment]
How would you like us to address this? Should we make the prover choices completely case-insensitive?

**Comment by weaversa** [comment]
What about changing the `using` message?

**Comment by brianhuffman** [comment]
Oh, I hadn't even noticed that bit. I'll have to look through the code to see where the prover-name strings come from.

**Comment by weaversa** [comment]
Yeah, sorry for not being more descriptive... :-)

**Comment by brianhuffman** [comment]
I found the problem. It's the use of the function `show` on type `Data.SBV.Solver` in these two locations:
https://github.com/GaloisInc/cryptol/blob/a28e7b95f7f067e875ce16c5dfc578b1d89fd359/src/Cryptol/Symbolic/SBV.hs#L143
https://github.com/GaloisInc/cryptol/blob/a28e7b95f7f067e875ce16c5dfc578b1d89fd359/src/Cryptol/Symbolic/SBV.hs#L170

The output of `show` is based on the names of the constructors of the haskell `Solver` datatype (`Z3`, `Yices`, `Boolector`, `CVC4`, `MathSAT`, and `ABC`), which must be capitalized according to haskell lexical conventions for data constructors.

Instead of the compiler-generated `show` function, we should be using our own special function of type `Solver -> String` that matches the solver names in the `proverConfigs` table.
https://github.com/GaloisInc/cryptol/blob/a28e7b95f7f067e875ce16c5dfc578b1d89fd359/src/Cryptol/Symbolic/SBV.hs#L71-L78

**Comment by weaversa** [comment]
There are more `prover=` strings than in that table. Will there be some distinction between z3 and sbv-z3. What about w4?

**Comment by robdockins** [comment]
I've made the solver selection string case insensitive in #788. I think that resolves the most egregious UX issue here.  Feel free to reopen if others think that more needs to be done.

For the moment `z3` is the same as `sbv-z3`, and likewise for the others.  Eventually, we may switch the default to use the `w4` versions instead.
