### ISSUE TITLE
:dumptests doesn't work for return types other than `Bit`

### ISSUE THREAD

**Issue by brianhuffman** [GaloisInc/cryptol#946]
```
Cryptol> :dumptests "test" \(x : [32]) -> x + 1

The expression is not of a testable type.
Type: [32] -> [32]
```

`:dumptests` only seems to support functions that return type `Bit`. I'm feeling like supporting expressions in general (not just theorems) would be helpful. Here I just want to generate some input/output pairs for a function so that when I modify/optimize/etc it I can test to see if I've messed it up.

_Originally posted by @weaversa in https://github.com/GaloisInc/cryptol/issues/611#issuecomment-638444878_

**Comment by brianhuffman** [comment]
Based on this comment in `Cryptol/Testing/Random.hs`, it's clear that this feature is supposed to work for non-`Bit` return types. Also these types used to work with `:dumptests` in version 2.7.
https://github.com/GaloisInc/cryptol/blob/ee0f60cd7f51b1ad96de79ce07ba4c55350458e2/src/Cryptol/Testing/Random.hs#L106-L118

**Comment by brianhuffman** [comment]
Bisecting shows that 64423cbcdcccef0a94e07ab8fd788d8ed07b1ad6 (one of mine; a fix for #615) is the first bad commit.

**Comment by brianhuffman** [comment]
It looks like there's a copy-and-paste error in the definition of `dumpableType`, which was based on the previously-existing function `testableTypeGenerators`. The call to `testableTypeGenerators` on line 114 should actually be a recursive call to `dumpableType` instead.

**Comment by weaversa** [comment]
I’ve been thinking about dumptest recently and ran across some work on automated sampling. I’m just going to paste the references here, but the gist would be to enhance dumptests so that it generated tests based on the structure of the function, rather than purely random tests. It seems like the current research uses SMT techniques to generate good tests, which facilitates integration into Cryptol.

https://people.eecs.berkeley.edu/~rtd/papers/GuidedSampler.pdf

https://arxiv.org/pdf/1905.05358.pdf
