### ISSUE TITLE
type-level primitive for helping padding constraints

### ISSUE THREAD

**Issue by dylanmc** [GaloisInc/cryptol#96]
A pattern that happens a lot when calculating the constraints for padding, is to calculate the ceiling-div - to calculate the number of blocks a message takes. A type-level primitive that computes ceiling div would be really handy and would tidy up the type constraints.

**Comment by dylanmc** [comment]
Let's capture current thinking and try to get consensus on how to proceed here. Yav thought of type-level divMod as one idea, but I think there are others too.

**Comment by brianhuffman** [comment]
I had a conversation with @yav today about type primitives for padding. The idea is to have a ceiling-div operator along with a corresponding modulus/padding operator. They should satisfy the following properties, assuming `blocksize > 0`. (The operator names are just placeholders; we should discuss naming/syntax separately.)
```
padding msglen blocksize < blocksize
(ceildiv msglen blocksize) * blocksize - (padding msglen blocksize) = msglen
```
or equivalently
```
(ceildiv msglen blocksize) * blocksize = msglen + padding msglen blocksize
```
These are similar to the characteristic properties of div/mod, but with `-` instead of `+` :
```
(a % b) < b
(a / b) * b + (a % b) = a
```
It's possible to define `ceildiv` and `padding` using the pre-existing Cryptol type operators:
```
ceildiv msglen blocksize = (msglen + (blocksize - 1)) / blocksize
padding msglen blocksize = (blocksize - (msglen % blocksize)) % blocksize
```
but these definitions are not very nice for solvers to handle.

To implement `ceildiv` and `padding` in a solver, my idea was to use the following definitions instead, which make sense in a theory of integer arithmetic:
```
ceildiv msglen blocksize = - ((- msglen) / blocksize)
padding msglen blocksize = (- msglen) % blocksize
```

**Comment by brianhuffman** [comment]
Note: The above definitions of `ceildiv` and `padding` in terms of `/` and `%` on negative integers only work correctly if the round-towards-negative-infinity variants of `/` and `%` are used.

**Comment by brianhuffman** [comment]
How should we define `ceildiv` and `padding` if either argument is `inf`? We could leave them undefined, or we could define them consistently so that they are the minimum values that satisfy the defining equation:
```
(ceildiv msglen blocksize) * blocksize = msglen + padding msglen blocksize
```
This would require
```
ceildiv inf inf = 1
padding inf inf = 0
ceildiv inf blocksize = inf  // for finite, non-zero blocksize
padding inf blocksize = 0 // for finite, non-zero blocksize
ceildiv 0 inf = 0
padding 0 inf = 0
ceildiv msglen inf = 1 // for finite, non-zero msglen
padding msglen inf = inf // for finite, non-zero msglen
```
We should leave `ceildiv` and `padding` undefined for `blocksize = 0`, because there is no solution to the defining equation in that case.

**Comment by yav** [comment]
I think that it would be good if `ceildiv x y` is the same as `div (x + y - 1) y`.

Currently `div` does not allow `inf` in its first argument, because that makes it easy to say when `div` is defined: `(fin x, y >= 1)`.  The nice thing about this is that it does not require `or` to define, so it fits as a normal constraint in our system.    This wouldn't be a problem, of course, if we were to add the other cases for `div`, although are they really useful? 

By the way, I am not seeing why `ceidiv inf inf = 1` is implied by the defining equation. It seems to me that `ceildiv inf inf * inf = inf + padding inf inf`  would be satisfied for any non 0 definition of `ceildiv inf inf`

**Comment by yav** [comment]
Also, if we are going to call the second one `padding`, perhaps the first one should be called `blocks`?  Otherwise, perhaps we should go with `ceilmod`.   I kind of like `blocks` and `padding` better, as Cryptol is supposed to be a DSL, but of course we could add type synonyms either way.

**Comment by weaversa** [comment]
I really like your idea of having `padding` and `blocks` as type synonyms.

What would the type of a hash function look like using these? Anyone want to take a quick stab at SHA256 or 384?

**Comment by jpziegler** [comment]
How about `pdng` and `blck`? Save those English word identifiers for the user.

**Comment by weaversa** [comment]
I think it's better for Cryptol to provide the nice names, especially if you want people to use them. Case-in-point: `Word`.

**Comment by weaversa** [comment]
@brianhuffman Will you provide a small example here?

**Comment by brianhuffman** [comment]
After seeing the `blocks` and `padding` operators in use, I'm having second thoughts about the syntax. The names are not quite self-explanatory; in particular they don't give the reader any intuition about what the argument order is. Also the relationship they have to `(/)` and `(%)` is not obvious. Finally, they just look a lot like user-defined type synonyms; it's not obvious from the names that they are built-in primitives; `blocks` and `padding` are the kind of names that Cryptol programmers are likely to want to use for themselves.

I decided that I prefer to use infix operators: `a /^ b` instead of `blocks a b`, and `a %^ b` instead of `padding a b`. This addresses most of my concerns: As infix operators, they are obviously primitives and not user-defined types. The operator names make the connection to `(/)` and `(%)` clear, and suggest that the right argument is a modulus. The operator names are still not quite self-explanatory, but I don't think they're too bad: the `^` on `/^` points up, and suggests "rounding up". Finally, we can keep the popular names `blocks` and `padding` available for users.

The defining properties of the operators can now be written like this:
```
(a /^ b) * b = a + (a %^ b)
(a %^ b) < b
```

I already added this change to my pull request (#453, 7e34c25e4dbd13725631f8c4f2b2e938ef2643dd), but if people still prefer the `blocks` and `padding` syntax, it would be easy to declare those as type synonyms.

**Comment by brianhuffman** [comment]
@weaversa here's an example of a padding function that's polymorphic over block size:
```
pad : {a, b} (fin a, fin b, b >= 1) => [a] -> [a /^ b][b]
pad x = split (x # (zero : [a %^ b]))
```
(Note that the `b >= 1` constraint is important, because `/^` and `%^` are undefined when `b` is 0. The example fails to type check if that constraint is missing.)

**Comment by LeventErkok** [comment]
Go full unicode with mixfix operators and properly do ceiling/floor etc. Then you can do: `⌈x/32⌉` A nice analogue to `[x]`. 

Kind of annoying to type maybe, but would render real nice in documents!

**Comment by brianhuffman** [comment]
I merged the blocks-padding branch this morning, so I'm closing the ticket.

**Comment by dylanmc** [comment]
+1 !
