### ISSUE TITLE
Windows installer includes too many files?

### ISSUE THREAD

**Issue by atomb** [GaloisInc/cryptol#977]
The Windows `.msi` installer we produce for releases is 4x the size of the corresponding tarball. It may partly be using less powerful compression, but I'm suspicious that it might include multiple copies of the binaries, in different locations.

**Comment by RyanGlScott** [comment]
I see what is going on here. The culprit is this line in `.github/wix.ps1`:

https://github.com/GaloisInc/cryptol/blob/34bd3292764925aea3622815305899a0a2d28f7e/.github/wix.ps1#L1

The use of `dir "$pwd"` causes every single file in the current checkout to be included, which is far more than what we want. I think the appropriate thing to do is to instead use `dir "$pwd/dist"` after a call to `.github/ci.sh bundle_files`, which only includes the files that we want for a binary distribution. I've tested this idea locally, and it successfully reduces the size of the resulting `cryptol.msi` file to 44.5 MB, which is comparable in size to a `.tar.gz` bindist.
